In [1]:
import io
import numpy as np
import cv2
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from copy import deepcopy
import skimage
from skimage.io import imread
import scipy
import basicpy
import tifffile
from tqdm import tqdm
# from descartes import PolygonPatch
import geopandas as gpd
import basicpy

import sys
sys.path.append('/home/icb/lion.gleiter/projects/organoid_sam/SAM_with_Detection_Head')

from util.box_ops_numpy import mask_to_boxes, cxcywh_to_xyxy, xyxy_to_cxcywh, plot_boxes
from util import dataloading as dl
from util import postprocessing as pp
from util.samos import SAMOS

base_datadir = Path('/ictstr01/groups/shared/users/lion.gleiter/organoid_sam/original_data/')
results_dir = Path('/ictstr01/groups/shared/users/lion.gleiter/organoid_sam/results')

%load_ext autoreload
%autoreload 2

In [2]:
# samos = SAMOS(checkpoint_path='/ictstr01/groups/shared/users/lion.gleiter/organoid_sam/checkpoints_trained/DetectionHead_SAM_large_OrganoID_train_MultiOrg_train_macros_MultiOrg_train_normal_OrgaExtractor_train_OrgaQuant_train_OrgaSegment_train_Tellu_train_NewData_train_ablation_dataset_5_pre_OI_NeurIPS_True_32_200/DetectionHead_SAM_large_OrganoID_train_MultiOrg_train_macros_MultiOrg_train_normal_OrgaExtractor_train_OrgaQuant_train_OrgaSegment_train_Tellu_train_NewData_train_ablation_dataset_5_pre_OI_NeurIPS_True_32_200-best_epoch=449-val_loss=5.28.ckpt')

In [3]:
# last epoch
samos = SAMOS(checkpoint_path='/ictstr01/groups/shared/users/lion.gleiter/organoid_sam/checkpoints_trained/DetectionHead_SAM_large_OrganoID_train_MultiOrg_train_macros_MultiOrg_train_normal_OrgaExtractor_train_OrgaQuant_train_OrgaSegment_train_Tellu_train_NewData_train_ablation_dataset_5_pre_OI_NeurIPS_True_32_200/DetectionHead_SAM_large_OrganoID_train_MultiOrg_train_macros_MultiOrg_train_normal_OrgaExtractor_train_OrgaQuant_train_OrgaSegment_train_Tellu_train_NewData_train_ablation_dataset_5_pre_OI_NeurIPS_True_32_200-last_epoch=499-val_loss=5.44.ckpt')

/home/icb/lion.gleiter/projects/organoid_sam/segment-anything/segment-anything/segment_anything/build_sam.py:105: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(f)

In [4]:
# samos = SAMOS(checkpoint_path='/ictstr01/groups/shared/users/lion.gleiter/organoid_sam/checkpoints_trained/DetectionHead_SAM_large_OrganoID_train_MultiOrg_train_macros_MultiOrg_train_normal_OrgaExtractor_train_OrgaQuant_train_OrgaSegment_train_Tellu_train_NewData_train_added_eval_True_32_200/DetectionHead_SAM_large_OrganoID_train_MultiOrg_train_macros_MultiOrg_train_normal_OrgaExtractor_train_OrgaQuant_train_OrgaSegment_train_Tellu_train_NewData_train_added_eval_True_32_200-best_epoch=649-val_loss=4.83.ckpt')

In [5]:
# retrained last epoch
# samos = SAMOS(checkpoint_path='/ictstr01/groups/shared/users/lion.gleiter/organoid_sam/checkpoints_trained/DetectionHead_SAM_large_OrganoID_train_MultiOrg_train_macros_MultiOrg_train_normal_OrgaExtractor_train_OrgaQuant_train_OrgaSegment_train_Tellu_train_NewData_train_added_eval_True_32_200/DetectionHead_SAM_large_OrganoID_train_MultiOrg_train_macros_MultiOrg_train_normal_OrgaExtractor_train_OrgaQuant_train_OrgaSegment_train_Tellu_train_NewData_train_added_eval_True_32_200-last_epoch=799-val_loss=4.93.ckpt')

In [6]:
def show_points(coords, labels, ax, marker_size=375):
    pos_points = coords[labels==1]
    neg_points = coords[labels==0]
    ax.scatter(pos_points[:, 0], pos_points[:, 1], color='green', marker='*', s=marker_size, edgecolor='white', linewidth=1.25)
    ax.scatter(neg_points[:, 0], neg_points[:, 1], color='red', marker='*', s=marker_size, edgecolor='white', linewidth=1.25)   
    
def show_box(box, ax, color='red'):
    y_min, x_min, y_max, x_max = box
    
    # Calculate width and height of the box
    width = x_max - x_min
    height = y_max - y_min

    ax.add_patch(plt.Rectangle((x_min, y_min), width, height, edgecolor=color, facecolor=(0,0,0,0), lw=2))

def show_mask(contour, ax, random_color=False):
    if random_color:
        color = np.concatenate([np.random.random(3), np.array([0.4])], axis=0)
    else:
        color = np.array([30/255, 184/255, 255/255, 0.4])

    contour = gpd.GeoSeries(contour)
    contour.plot(color=color, ax=ax)

def visualize(im, contours, boxes, random_color=True, box_color='red', format='yxyx_px', ax=None, **fig_kwargs):
    # Format boxes
    H, W = im.shape[:2]

    if format=='cycxhw_01':
        # boxes are in cycxhw format normalized by the longest image side. Converts to min/max coordinates in pixels.
        original_boxes = cxcywh_to_xyxy(boxes) * max(H, W)
    elif format=='cycxhw_px':
        # boxes are in cycxhw format in pixels. Converts to min/max coordinates in pixels.
        original_boxes = cxcywh_to_xyxy(boxes)
    elif format=='yxyx_01':
        # boxes are in min/max coordinates normalized by the longest image side. Converts to min/max coordinates in pixels.
        original_boxes = boxes * max(H, W)
    elif format=='yxyx_px':
        # boxes are in min/max coordinates in pixels. No conversion necessary.
        original_boxes = boxes
    else:
        raise ValueError(format)

    if ax is None:
        fig, ax = plt.subplots(1, 1, **fig_kwargs)
    
    ax.imshow(im)
    ax.axis(False)
    for i in range(original_boxes.shape[0]):
        show_mask(contours[i], ax, random_color=random_color)
        show_box(original_boxes[i], ax, color=box_color)

## OrganoID

In [7]:
ds = dl.OrganoID(split='test')
pq_data = []
for idx in range(len(ds)):
    im, gt_mask, gt_boxes, im_path, im_ID = ds[idx]
    im, flatfield = dl.normalize(im)

    H, W = im.shape[:2]
    patch_size = int(np.ceil(max(H, W) * 7 / 12))
    print(patch_size)

    contours, boxes, scores = samos.forward(im, patch_size=patch_size, predict_masks=True)
    for thres in [0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.95]:
        contours, boxes, scores = samos.set_threshold(conf_thres=thres, predict_masks=True)
        if contours is not None:
            iou_matrix = pp.compute_iou_matrix_segmentation_contours(contours, pp.convert_mask_to_binary(gt_mask).astype(np.uint8))
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_segmentation_from_iou_matrix(iou_matrix=iou_matrix)
        else:
            iou_matrix = pp.compute_iou_matrix_detection(boxes, gt_boxes)
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_detection_from_iou_matrix(iou_matrix=iou_matrix)

        print("Threshold", thres)
        print("tp, fp, fn, pq, precision, recall, f1_score, mean_iou:", tp, fp, fn, pq, precision, recall, f1_score, mean_iou)
        pq_data.append((f'{thres:4.2f}', pq, f1_score, precision, recall, mean_iou))


        fig, ax = plt.subplots(1, 1, figsize=(12*4, 12*4), dpi=200)
        plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
        plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
        plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
        plot_dir.mkdir(exist_ok=True)
        plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_{int(thres*100)}.png', dpi=200)
        plt.close('all')

    # fig, ax = plt.subplots(1, 1, figsize=(10, 10), dpi=80)
    # plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    # plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')

pq_data = pd.DataFrame(data=pq_data, columns=["thres", "pq", "f1_score", "precision", "recall", "iou"])
pq_data.to_csv(results_dir / f'test_metrics_added_eval_{str(ds)}_{ds.split}.csv', index=False)

pq_data.groupby('thres').mean()
# plot_boxes(im, boxes, format='yxyx_px')

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

976
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 64 107 116 0.2758711760212687 0.3742690058479532 0.35555555555555557 0.36467236467236464 0.7564904904958228
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 61 89 119 0.2815202601479259 0.4066666666666667 0.3388888888888889 0.36969696969696975 0.76148922826898
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 59 71 121 0.2911250693925507 0.45384615384615384 0.3277777777777778 0.3806451612903226 0.7648200975567009
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 52 125 0.2994225568747437 0.514018691588785 0.3055555555555556 0.3832752613240418 0.7812206711186493
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 50 44 130 0.2875695909761604 0.5319148936170213 0.2777777777777778 0.36496350364963503 0.7879406792746795
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 43 36 137 0.26428264165667786 0.5443037974683544 0.2388888888888889 0.33204633204633205 0.7959209789427857
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 36 14 144 0.2562414522999078 0.72 0.2 0.3130434782608696 0.8185490837358166
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 70 66 9 0.5603459999469422 0.5147058823529411 0.8860759493670886 0.6511627906976745 0.8605313570613755
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 69 56 10 0.5823724411939895 0.552 0.8734177215189873 0.6764705882352942 0.8608983913302453
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 67 45 12 0.6055967370489593 0.5982142857142857 0.8481012658227848 0.7015706806282722 0.8632013192265017
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 37 13 0.626391605762669 0.6407766990291263 0.8354430379746836 0.7252747252747253 0.8636611534000435
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 28 13 0.6589784523052356 0.7021276595744681 0.8354430379746836 0.7630057803468209 0.8636611534000435
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 18 13 0.6994065782135321 0.7857142857142857 0.8354430379746836 0.8098159509202455 0.8636611534000435
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 7 24 0.6864309603135166 0.8870967741935484 0.6962025316455697 0.7801418439716311 0.8798796854927804
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 52 1 0.5549220504662298 0.5047619047619047 0.9814814814814815 0.6666666666666667 0.8323830756993447
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 41 1 0.5961662569198009 0.5638297872340425 0.9814814814814815 0.7162162162162162 0.8323830756993447
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 36 1 0.6170112309379757 0.5955056179775281 0.9814814814814815 0.7412587412587414 0.8323830756993447
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 25 2 0.6608268725942352 0.6753246753246753 0.9629629629629629 0.7938931297709924 0.8323876952869694
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 19 2 0.6925465624787586 0.7323943661971831 0.9629629629629629 0.832 0.8323876952869694
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 13 2 0.7274648765533178 0.8 0.9629629629629629 0.8739495798319328 0.8323876952869694
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 51 4 3 0.7797770575668476 0.9272727272727272 0.9444444444444444 0.9357798165137615 0.8332911693606508
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 68 3 0.30184866483914596 0.25274725274725274 0.8846153846153846 0.39316239316239315 0.7677455170908712
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 53 3 0.3462381743743145 0.3026315789473684 0.8846153846153846 0.45098039215686275 0.7677455170908712
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 43 3 0.3838727585454356 0.3484848484848485 0.8846153846153846 0.5 0.7677455170908712
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 36 4 0.40668742632222576 0.3793103448275862 0.8461538461538461 0.5238095238095238 0.7764032684333401
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 31 4 0.4324271368489489 0.41509433962264153 0.8461538461538461 0.5569620253164558 0.7764032684333401
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 23 5 0.4612904089758796 0.4772727272727273 0.8076923076923077 0.6000000000000001 0.7688173482931326
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 15 6 0.501544578192486 0.5714285714285714 0.7692307692307693 0.6557377049180327 0.7648554817435411
438
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 20 0 0.5731665590343088 0.5238095238095238 1.0 0.6875000000000001 0.8336968131408128
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 13 1 0.6274894139828582 0.6176470588235294 0.9545454545454546 0.75 0.8366525519771442
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 11 1 0.6507297626488899 0.65625 0.9545454545454546 0.7777777777777778 0.8366525519771442
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 10 1 0.663007682698869 0.6774193548387096 0.9545454545454546 0.7924528301886793 0.8366525519771442
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 10 1 0.663007682698869 0.6774193548387096 0.9545454545454546 0.7924528301886793 0.8366525519771442
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 8 1 0.6890079839811776 0.7241379310344828 0.9545454545454546 0.823529411764706 0.8366525519771442
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 5 3 0.6917586131069555 0.7916666666666666 0.8636363636363636 0.8260869565217391 0.8373920053399988
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 41 1 0.44710161046040403 0.3880597014925373 0.9629629629629629 0.553191489361702 0.808222141986115
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 35 1 0.47758581117361343 0.4262295081967213 0.9629629629629629 0.5909090909090909 0.808222141986115
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 27 1 0.5205965533357929 0.49056603773584906 0.9629629629629629 0.65 0.8009177743627584
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 20 1 0.5705167707789511 0.5652173913043478 0.9629629629629629 0.7123287671232876 0.8009177743627584
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 17 3 0.5728935651202653 0.5853658536585366 0.8888888888888888 0.7058823529411764 0.8115992172537093
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 14 4 0.5813049324208015 0.6216216216216216 0.8518518518518519 0.7187499999999999 0.8087720798898108
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 6 0.6152196467652105 0.7777777777777778 0.7777777777777778 0.7777777777777778 0.7909966886981278
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 12 10 0.5697235213427492 0.6571428571428571 0.696969696969697 0.676470588235294 0.84219998807189
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 10 10 0.5869878704743475 0.696969696969697 0.696969696969697 0.696969696969697 0.84219998807189
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 7 12 0.594053957464425 0.75 0.6363636363636364 0.6885245901639345 0.8627926525078554
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 12 0.6039548567554988 0.7777777777777778 0.6363636363636364 0.7000000000000001 0.8627926525078554
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 4 12 0.6247808862987918 0.84 0.6363636363636364 0.7241379310344828 0.8627926525078554
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 4 13 0.6069781845896316 0.8333333333333334 0.6060606060606061 0.7017543859649124 0.864943913040225
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 2 15 0.5888948931389513 0.9 0.5454545454545454 0.679245283018868 0.8669841482323448
299
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 14 9 0.5551036051470244 0.6744186046511628 0.7631578947368421 0.7160493827160495 0.7752308968432582
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 11 9 0.5764537438065254 0.725 0.7631578947368421 0.7435897435897436 0.7752308968432582
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 7 9 0.6076134056339051 0.8055555555555556 0.7631578947368421 0.7837837837837838 0.7752308968432582
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 6 12 0.5835012734716382 0.8125 0.6842105263157895 0.742857142857143 0.7854824835195129
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 5 14 0.5684434639797412 0.8275862068965517 0.631578947368421 0.716417910447761 0.7934523351383888
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 3 14 0.5859340321021947 0.8888888888888888 0.631578947368421 0.7384615384615385 0.7934523351383888
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 1 19 0.5271950472390986 0.95 0.5 0.6551724137931034 0.8046661247333611
613
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 47 60 4 0.48535025865836007 0.4392523364485981 0.9215686274509803 0.5949367088607594 0.8158014985959668
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 47 52 4 0.5112356057868059 0.47474747474747475 0.9215686274509803 0.6266666666666666 0.8158014985959668
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 46 44 5 0.5294134542310958 0.5111111111111111 0.9019607843137255 0.652482269503546 0.8113836635498315
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 44 28 7 0.5812565791658437 0.6111111111111112 0.8627450980392157 0.7154471544715448 0.8124381731522589
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 43 28 8 0.574963941836602 0.6056338028169014 0.8431372549019608 0.7049180327868853 0.8156465221402959
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 39 16 12 0.5953074972408575 0.7090909090909091 0.7647058823529411 0.7358490566037736 0.8090076244555243
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 34 7 17 0.6006003304950215 0.8292682926829268 0.6666666666666666 0.7391304347826086 0.8125769177285586
1195
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 89 64 24 0.5484881967555755 0.5816993464052288 0.7876106194690266 0.6691729323308271 0.8196509007695679
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 88 54 25 0.5674150244395908 0.6197183098591549 0.7787610619469026 0.6901960784313725 0.8221069956369071
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 87 42 26 0.5904155415931948 0.6744186046511628 0.7699115044247787 0.71900826446281 0.8211526498020295
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 80 33 33 0.5910453025983493 0.7079646017699115 0.7079646017699115 0.7079646017699115 0.8348514899201683
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 75 25 38 0.5909939687752785 0.75 0.6637168141592921 0.7042253521126761 0.8392114356608956
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 71 16 42 0.5988852665747906 0.8160919540229885 0.6283185840707964 0.71 0.8435003754574516
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 62 7 51 0.5770305717405755 0.8985507246376812 0.5486725663716814 0.6813186813186812 0.8469319681998769

             pq  f1_score  precision    recall       iou
thres
0.50   0.487192  0.597299   0.491087  0.824000  0.811195
0.60   0.515346  0.631170   0.538544  0.815637  0.812273
0.70   0.539043  0.659505   0.588395  0.803088  0.813628
0.80   0.558661  0.679730   0.636142  0.775891  0.818681
0.85   0.566661  0.686497   0.666754  0.754057  0.821975
0.90   0.580986  0.704416   0.720046  0.728205  0.821712
0.95   0.582469  0.704343   0.825306  0.651209  0.825612

In [ ]:
ds = dl.OrganoID(split='test_mouse')
pq_data = []
for idx in range(len(ds)):
    im, gt_mask, gt_boxes, im_path, im_ID = ds[idx]
    im, flatfield = dl.normalize(im)

    H, W = im.shape[:2]
    patch_size = int(np.ceil(max(H, W) * 7 / 12))
    print(patch_size)

    contours, boxes, scores = samos.forward(im, patch_size=patch_size, predict_masks=True)
    for thres in [0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.95]:
        contours, boxes, scores = samos.set_threshold(conf_thres=thres, predict_masks=True)
        if contours is not None:
            iou_matrix = pp.compute_iou_matrix_segmentation_contours(contours, pp.convert_mask_to_binary(gt_mask).astype(np.uint8))
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_segmentation_from_iou_matrix(iou_matrix=iou_matrix)
        else:
            iou_matrix = pp.compute_iou_matrix_detection(boxes, gt_boxes)
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_detection_from_iou_matrix(iou_matrix=iou_matrix)

        print("Threshold", thres)
        print("tp, fp, fn, pq, precision, recall, f1_score, mean_iou:", tp, fp, fn, pq, precision, recall, f1_score, mean_iou)
        pq_data.append((f'{thres:4.2f}', pq, f1_score, precision, recall, mean_iou))


        fig, ax = plt.subplots(1, 1, figsize=(12*4, 12*4), dpi=200)
        plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
        plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
        plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
        plot_dir.mkdir(exist_ok=True)
        plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_{int(thres*100)}.png', dpi=200)
        plt.close('all')

    # fig, ax = plt.subplots(1, 1, figsize=(10, 10), dpi=80)
    # plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    # plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')

pq_data = pd.DataFrame(data=pq_data, columns=["thres", "pq", "f1_score", "precision", "recall", "iou"])
pq_data.to_csv(results_dir / f'test_metrics_added_eval_{str(ds)}_{ds.split}.csv', index=False)

pq_data.groupby('thres').mean()
# plot_boxes(im, boxes, format='yxyx_px')

1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 11 2 0.49068046436435847 0.47619047619047616 0.8333333333333334 0.6060606060606061 0.8096227662011914
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 9 2 0.5223372685168977 0.5263157894736842 0.8333333333333334 0.6451612903225806 0.8096227662011914
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 8 2 0.5397485108007943 0.5555555555555556 0.8333333333333334 0.6666666666666667 0.8096227662011914
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 6 2 0.5783019758579939 0.625 0.8333333333333334 0.7142857142857143 0.8096227662011914
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 5 2 0.5997205675564381 0.6666666666666666 0.8333333333333334 0.7407407407407408 0.8096227662011914
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 1 2 0.7040197966966882 0.9090909090909091 0.8333333333333334 0.8695652173913043 0.8096227662011914
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 8 0 4 0.6807878490080645 1.0 0.6666666666666666 0.8 0.8509848112600806
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 13 0 0.6205973542165425 0.5806451612903226 1.0 0.7346938775510204 0.844701954350294
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 12 0 0.6335264657627205 0.6 1.0 0.7499999999999999 0.844701954350294
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 8 1 0.668110518088824 0.68 0.9444444444444444 0.7906976744186047 0.8449633022888069
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 6 2 0.6732969319454859 0.7272727272727273 0.8888888888888888 0.7999999999999999 0.8416211649318573
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 6 2 0.6732969319454859 0.7272727272727273 0.8888888888888888 0.7999999999999999 0.8416211649318573
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 14 5 4 0.6410068734765507 0.7368421052631579 0.7777777777777778 0.7567567567567567 0.8470447970940135
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 3 7 0.5766423136396069 0.7857142857142857 0.6111111111111112 0.6875000000000001 0.8387524562030646
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 68 62 14 0.5337546052374306 0.5230769230769231 0.8292682926829268 0.6415094339622641 0.8320292375759948
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 47 16 0.5620216675566486 0.584070796460177 0.8048780487804879 0.676923076923077 0.8302592816177763
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 63 36 19 0.5788679979757769 0.6363636363636364 0.7682926829268293 0.6961325966850828 0.8315484732826637
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 56 25 26 0.5725956381854637 0.691358024691358 0.6829268292682927 0.6871165644171778 0.8333311520020587
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 19 27 0.5839030172281514 0.7432432432432432 0.6707317073170732 0.7051282051282052 0.8280806426144693
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 46 12 36 0.5397148771364325 0.7931034482758621 0.5609756097560976 0.6571428571428573 0.8213052478163104
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 30 7 52 0.4153695953916058 0.8108108108108109 0.36585365853658536 0.504201680672269 0.8238163641933515
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 11 1 0.6397222372389865 0.6071428571428571 0.9444444444444444 0.7391304347826088 0.8655065562645111
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 5 1 0.7356805728248345 0.7727272727272727 0.9444444444444444 0.85 0.8655065562645111
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 4 1 0.7545441772562405 0.8095238095238095 0.9444444444444444 0.8717948717948718 0.8655065562645111
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 3 1 0.77440060297351 0.85 0.9444444444444444 0.8947368421052632 0.8655065562645111
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 2 1 0.7952720736231709 0.8947368421052632 0.9444444444444444 0.918918918918919 0.8654431389428625
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 2 2 0.7765937038718914 0.8888888888888888 0.8888888888888888 0.8888888888888888 0.8736679168558779
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 15 2 3 0.752462251692634 0.8823529411764706 0.8333333333333334 0.8571428571428571 0.8778726269747398
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 7 7 0.6047716794346334 0.7407407407407407 0.7407407407407407 0.7407407407407407 0.816441767236755
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 6 8 0.5976363108691992 0.76 0.7037037037037037 0.7307692307692308 0.8178181096104831
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 6 9 0.5816305258759004 0.75 0.6666666666666666 0.7058823529411765 0.8239765783241922
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 3 11 0.5733159151830802 0.8421052631578947 0.5925925925925926 0.6956521739130435 0.8241416280756778
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 15 3 12 0.5455385347808619 0.8333333333333334 0.5555555555555556 0.6666666666666667 0.818307802171293
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 14 2 13 0.5280536919989723 0.875 0.5185185185185185 0.6511627906976744 0.8109395984269933
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 2 15 0.48710467319953904 0.8571428571428571 0.4444444444444444 0.5853658536585367 0.8321371500492125
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 8 9 0 0.569986499457862 0.47058823529411764 1.0 0.6399999999999999 0.8906039054029092
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 8 8 0 0.5937359369352728 0.5 1.0 0.6666666666666666 0.8906039054029092
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 8 7 0 0.6195505428889804 0.5333333333333333 1.0 0.6956521739130436 0.8906039054029092
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 8 5 0 0.6785553564974547 0.6153846153846154 1.0 0.761904761904762 0.8906039054029092
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 8 3 0 0.7499822361287657 0.7272727272727273 1.0 0.8421052631578948 0.8906039054029092
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 8 2 0 0.7916479159136971 0.8 1.0 0.888888888888889 0.8906039054029092
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 8 2 0 0.7916479159136971 0.8 1.0 0.888888888888889 0.8906039054029092
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 58 54 14 0.5441332583056682 0.5178571428571429 0.8055555555555556 0.6304347826086957 0.8631079269676116
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 56 50 16 0.5430539411085265 0.5283018867924528 0.7777777777777778 0.6292134831460674 0.8630678706903367
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 56 43 16 0.5652842193995188 0.5656565656565656 0.7777777777777778 0.6549707602339181 0.8630678706903367
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 39 17 0.5713083758232684 0.5851063829787234 0.7638888888888888 0.6626506024096385 0.8621562762423869
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 54 33 18 0.5850934625391863 0.6206896551724138 0.75 0.679245283018868 0.8613875976271353
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 48 26 24 0.563750590713719 0.6486486486486487 0.6666666666666666 0.6575342465753425 0.8573706900437811
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 40 12 32 0.555036266649603 0.7692307692307693 0.5555555555555556 0.6451612903225806 0.8603062133068848
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 13 0 0.7033361172639809 0.6388888888888888 1.0 0.7796610169491525 0.9021050199690189
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 13 0 0.7033361172639809 0.6388888888888888 1.0 0.7796610169491525 0.9021050199690189
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 12 0 0.7022015141401659 0.6571428571428571 1.0 0.7931034482758621 0.8853845178289047
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 11 0 0.7145208389496424 0.6764705882352942 1.0 0.8070175438596492 0.8853845178289047
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 10 0 0.7272801396451717 0.696969696969697 1.0 0.8214285714285715 0.8853845178289047
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 9 0 0.7405034149114476 0.71875 1.0 0.8363636363636363 0.8853845178289047
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 6 0 0.7832247657717234 0.7931034482758621 1.0 0.8846153846153846 0.8853845178289047
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 8 6 0.5552554202259806 0.6666666666666666 0.7272727272727273 0.6956521739130435 0.7981796665748471
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 6 6 0.5804943029635251 0.7272727272727273 0.7272727272727273 0.7272727272727273 0.7981796665748471
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 4 6 0.6081368888189311 0.8 0.7272727272727273 0.761904761904762 0.7981796665748471
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 4 6 0.6081368888189311 0.8 0.7272727272727273 0.761904761904762 0.7981796665748471
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 2 6 0.6385437332598777 0.8888888888888888 0.7272727272727273 0.7999999999999999 0.7981796665748471
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 15 1 7 0.6226041134983881 0.9375 0.6818181818181818 0.7894736842105263 0.7886318770979582
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 1 10 0.54438420577166 0.9230769230769231 0.5454545454545454 0.6857142857142856 0.7938936334170043
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 6 7 0.6613103173604312 0.76 0.7307692307692307 0.7450980392156863 0.8875480575100525
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 6 7 0.6613103173604312 0.76 0.7307692307692307 0.7450980392156863 0.8875480575100525
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 4 8 0.6659807054875119 0.8181818181818182 0.6923076923076923 0.7500000000000001 0.8879742739833492
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 4 8 0.6659807054875119 0.8181818181818182 0.6923076923076923 0.7500000000000001 0.8879742739833492
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 3 8 0.6801505077319271 0.8571428571428571 0.6923076923076923 0.7659574468085107 0.8879742739833492
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 2 8 0.694936388334795 0.9 0.6923076923076923 0.7826086956521738 0.8879742739833492
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 15 2 11 0.6212011985759258 0.8823529411764706 0.5769230769230769 0.6976744186046512 0.8903883846254936
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 31 7 7 0.6862377781114696 0.8157894736842105 0.8157894736842105 0.8157894736842104 0.8411946957495433
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 30 6 8 0.6819836397427089 0.8333333333333334 0.7894736842105263 0.8108108108108109 0.8411131556826743
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 30 3 8 0.7107998498726825 0.9090909090909091 0.7894736842105263 0.8450704225352113 0.8411131556826743
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 3 9 0.7051354134601634 0.90625 0.7631578947368421 0.8285714285714286 0.8510254990036455
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 27 2 11 0.6987464682927581 0.9310344827586207 0.7105263157894737 0.8059701492537312 0.8669632106595332
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 1 14 0.6655406563132739 0.96 0.631578947368421 0.7619047619047619 0.8735221114111719
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 0 18 0.6031862576443608 1.0 0.5263157894736842 0.6896551724137931 0.8746200735843231
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 9 2 0.6856014012866414 0.6896551724137931 0.9090909090909091 0.7843137254901961 0.8741417866404678
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 7 2 0.7135851319514023 0.7407407407407407 0.9090909090909091 0.8163265306122449 0.8741417866404678
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 4 4 0.721453336267977 0.8181818181818182 0.8181818181818182 0.8181818181818182 0.881776299883083
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 4 5 0.7011330145898862 0.8095238095238095 0.7727272727272727 0.7906976744186046 0.8867270478636796
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 4 5 0.7011330145898862 0.8095238095238095 0.7727272727272727 0.7906976744186046 0.8867270478636796
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 15 2 7 0.6815576707091633 0.8823529411764706 0.6818181818181818 0.7692307692307693 0.8860249719219123
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 0 10 0.6412151394669695 1.0 0.5454545454545454 0.7058823529411764 0.9083881142448735
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 5 0 0.7090448988111441 0.6875 1.0 0.8148148148148148 0.8701914667227677
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 4 0 0.7363158564577266 0.7333333333333333 1.0 0.846153846153846 0.8701914667227677
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 3 0 0.7657684907160356 0.7857142857142857 1.0 0.88 0.8701914667227677
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 2 0 0.7976755111625371 0.8461538461538461 1.0 0.9166666666666666 0.8701914667227677
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 2 1 0.7535176486214347 0.8333333333333334 0.9090909090909091 0.8695652173913043 0.8665452959146499
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 2 1 0.7535176486214347 0.8333333333333334 0.9090909090909091 0.8695652173913043 0.8665452959146499
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 9 1 2 0.7406228032045341 0.9 0.8181818181818182 0.8571428571428572 0.8640599370719565
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 14 9 0 0.6337780323304755 0.6086956521739131 1.0 0.7567567567567568 0.8374923998652711
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 14 5 0 0.7105996120068968 0.7368421052631579 1.0 0.8484848484848484 0.8374923998652711
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 2 1 0.7460639508722771 0.8666666666666667 0.9285714285714286 0.896551724137931 0.8321482528960013
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 1 1 0.7727090919748584 0.9285714285714286 0.9285714285714286 0.9285714285714286 0.8321482528960013
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 1 1 0.7727090919748584 0.9285714285714286 0.9285714285714286 0.9285714285714286 0.8321482528960013
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 1 2 0.7345271868027284 0.9230769230769231 0.8571428571428571 0.888888888888889 0.8263430851530695
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 0 3 0.7501500985280619 1.0 0.7857142857142857 0.88 0.8524432937818885
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 4 0 0.7589848936168039 0.75 1.0 0.8571428571428571 0.8854823758862712
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 4 0 0.7589848936168039 0.75 1.0 0.8571428571428571 0.8854823758862712
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 3 0 0.7870954452322411 0.8 1.0 0.888888888888889 0.8854823758862712
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 3 0 0.7870954452322411 0.8 1.0 0.888888888888889 0.8854823758862712
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 3 0 0.7870954452322411 0.8 1.0 0.888888888888889 0.8854823758862712
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 0 1 0.8532761620871129 1.0 0.9166666666666666 0.9565217391304348 0.8920614421819817
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 0 2 0.8119874464103115 1.0 0.8333333333333334 0.9090909090909091 0.8931861910513426
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 6 0 0.723713815963475 0.6842105263157895 1.0 0.8125000000000001 0.8907246965704307
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 5 1 0.7160213287880063 0.7058823529411765 0.9230769230769231 0.8000000000000002 0.8950266609850078
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 4 1 0.7407117194358686 0.75 0.9230769230769231 0.8275862068965517 0.8950266609850078
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 4 1 0.7407117194358686 0.75 0.9230769230769231 0.8275862068965517 0.8950266609850078
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 4 1 0.7407117194358686 0.75 0.9230769230769231 0.8275862068965517 0.8950266609850078
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 4 1 0.7407117194358686 0.75 0.9230769230769231 0.8275862068965517 0.8950266609850078
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 3 2 0.731056720954975 0.7857142857142857 0.8461538461538461 0.8148148148148148 0.8972059757174692
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 35 14 2 0.7136166431382885 0.7142857142857143 0.9459459459459459 0.813953488372093 0.8767290187127544
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 35 10 2 0.7484272110962539 0.7777777777777778 0.9459459459459459 0.8536585365853658 0.8767290187127544
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 35 7 2 0.7768484975935799 0.8333333333333334 0.9459459459459459 0.8860759493670887 0.8767290187127544
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 35 7 2 0.7768484975935799 0.8333333333333334 0.9459459459459459 0.8860759493670887 0.8767290187127544
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 33 7 4 0.7558046194239804 0.825 0.8918918918918919 0.8571428571428571 0.8817720559946437
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 32 7 5 0.7396650557810827 0.8205128205128205 0.8648648648648649 0.8421052631578947 0.8783522537400357
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 28 5 9 0.6986393968210487 0.8484848484848485 0.7567567567567568 0.8000000000000002 0.8732992460263108
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 56 32 150 0.3187218258935861 0.6363636363636364 0.27184466019417475 0.38095238095238093 0.8366447929706636
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 44 23 162 0.26352547836807855 0.6567164179104478 0.21359223300970873 0.32234432234432236 0.8175279044827891
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 15 177 0.1862031282647593 0.6590909090909091 0.1407766990291262 0.23199999999999998 0.8025996907963763

             pq  f1_score  precision    recall       iou
thres
0.50   0.613804  0.714344   0.631884  0.864687  0.857635
0.60   0.632521  0.736424   0.675379  0.851493  0.856830
0.70   0.648156  0.754952   0.725676  0.830293  0.855713
0.80   0.652426  0.758483   0.759352  0.809615  0.859210
0.85   0.655524  0.761954   0.772825  0.791326  0.859055
0.90   0.655589  0.762292   0.821940  0.749542  0.858484
0.95   0.625124  0.720544   0.858036  0.659400  0.867173

:

In [7]:
ds = dl.OrganoID(split='test_only_mouse')
pq_data = []
for idx in range(len(ds)):
    im, gt_mask, gt_boxes, im_path, im_ID = ds[idx]
    im, flatfield = dl.normalize(im)

    H, W = im.shape[:2]
    patch_size = int(np.ceil(max(H, W) * 7 / 12))
    print(patch_size)

    contours, boxes, scores = samos.forward(im, patch_size=patch_size, predict_masks=True)
    for thres in [0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.95]:
        contours, boxes, scores = samos.set_threshold(conf_thres=thres, predict_masks=True)
        if contours is not None:
            iou_matrix = pp.compute_iou_matrix_segmentation_contours(contours, pp.convert_mask_to_binary(gt_mask).astype(np.uint8))
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_segmentation_from_iou_matrix(iou_matrix=iou_matrix)
        else:
            iou_matrix = pp.compute_iou_matrix_detection(boxes, gt_boxes)
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_detection_from_iou_matrix(iou_matrix=iou_matrix)

        print("Threshold", thres)
        print("tp, fp, fn, pq, precision, recall, f1_score, mean_iou:", tp, fp, fn, pq, precision, recall, f1_score, mean_iou)
        pq_data.append((f'{thres:4.2f}', pq, f1_score, precision, recall, mean_iou))


        fig, ax = plt.subplots(1, 1, figsize=(12*4, 12*4), dpi=200)
        plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
        plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
        plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
        plot_dir.mkdir(exist_ok=True)
        plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_{int(thres*100)}.png', dpi=200)
        plt.close('all')

    # fig, ax = plt.subplots(1, 1, figsize=(10, 10), dpi=80)
    # plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    # plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')

pq_data = pd.DataFrame(data=pq_data, columns=["thres", "pq", "f1_score", "precision", "recall", "iou"])
pq_data.to_csv(results_dir / f'test_metrics_added_eval_{str(ds)}_{ds.split}.csv', index=False)

pq_data.groupby('thres').mean()
# plot_boxes(im, boxes, format='yxyx_px')

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 10 1 0.5094869334035363 0.5238095238095238 0.9166666666666666 0.6666666666666667 0.7642304001053045
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 9 1 0.5254084000723969 0.55 0.9166666666666666 0.6874999999999999 0.7642304001053045
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 7 1 0.56043562674389 0.6111111111111112 0.9166666666666666 0.7333333333333334 0.7642304001053045
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 5 2 0.5838820189922579 0.6666666666666666 0.8333333333333334 0.7407407407407408 0.7882407256395482
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 5 2 0.5838820189922579 0.6666666666666666 0.8333333333333334 0.7407407407407408 0.7882407256395482
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 2 2 0.6568672713662901 0.8333333333333334 0.8333333333333334 0.8333333333333334 0.7882407256395482
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 8 1 4 0.6277868420077996 0.8888888888888888 0.6666666666666666 0.761904761904762 0.823970230135237
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 9 2 0.6648840490172745 0.64 0.8888888888888888 0.7441860465116279 0.8934379408669626
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 9 2 0.6648840490172745 0.64 0.8888888888888888 0.7441860465116279 0.8934379408669626
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 7 2 0.6973174172620196 0.6956521739130435 0.8888888888888888 0.7804878048780488 0.8934379408669626
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 15 5 3 0.7050826080984948 0.75 0.8333333333333334 0.7894736842105262 0.8931046369247599
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 14 5 4 0.6749620867015158 0.7368421052631579 0.7777777777777778 0.7567567567567567 0.8919141859984316
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 4 5 0.6650575008787335 0.7647058823529411 0.7222222222222222 0.7428571428571428 0.895269712721372
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 3 8 0.5834527063855552 0.7692307692307693 0.5555555555555556 0.6451612903225806 0.9043516948976107
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 72 56 10 0.5590588246512714 0.5625 0.8780487804878049 0.6857142857142857 0.8152941192831042
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 70 46 12 0.5814880878705575 0.603448275862069 0.8536585365853658 0.7070707070707071 0.8223902957026455
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 40 16 0.5764574545571051 0.6226415094339622 0.8048780487804879 0.7021276595744681 0.8210151625510285
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 59 28 23 0.5739875247115024 0.6781609195402298 0.7195121951219512 0.6982248520710059 0.8220668786122365
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 51 16 31 0.5644352649368222 0.7611940298507462 0.6219512195121951 0.6845637583892618 0.824518181133201
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 46 14 36 0.5363587665021674 0.7666666666666667 0.5609756097560976 0.6478873239436621 0.8278580961229105
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 32 7 50 0.43028277623063366 0.8205128205128205 0.3902439024390244 0.5289256198347106 0.8135033738110418
1512
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 10 1 0.6548373380689263 0.6296296296296297 0.9444444444444444 0.7555555555555556 0.8666964768559319
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 6 1 0.7187239076366264 0.7391304347826086 0.9444444444444444 0.8292682926829269 0.8666964768559319
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 5 1 0.7366920053275421 0.7727272727272727 0.9444444444444444 0.85 0.8666964768559319
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 2 1 0.7964237895432887 0.8947368421052632 0.9444444444444444 0.918918918918919 0.8666964768559319
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 2 1 0.7964237895432887 0.8947368421052632 0.9444444444444444 0.918918918918919 0.8666964768559319
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 1 1 0.8183330694383221 0.9444444444444444 0.9444444444444444 0.9444444444444444 0.8664703088170469
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 1 2 0.7953136288301277 0.9411764705882353 0.8888888888888888 0.9142857142857143 0.8698742815329521

             pq  f1_score  precision    recall       iou
thres
0.50   0.597067  0.713031   0.588985  0.907012  0.834915
0.60   0.622626  0.742006   0.633145  0.900915  0.836689
0.70   0.642726  0.766487   0.675533  0.888720  0.836345
0.80   0.664844  0.786840   0.747391  0.832656  0.842527
0.85   0.654926  0.775245   0.764860  0.794377  0.842842
0.90   0.669154  0.792131   0.827288  0.765244  0.844460
0.95   0.609209  0.712569   0.854952  0.625339  0.852925

In [8]:
ds = dl.OrganoID(split='test_ACC')
pq_data = []
for idx in range(len(ds)):
    im, gt_mask, gt_boxes, im_path, im_ID = ds[idx]
    im, flatfield = dl.normalize(im)

    H, W = im.shape[:2]
    patch_size = int(np.ceil(max(H, W) * 7 / 12))
    print(patch_size)

    contours, boxes, scores = samos.forward(im, patch_size=patch_size, predict_masks=True)
    for thres in [0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.95]:
        contours, boxes, scores = samos.set_threshold(conf_thres=thres, predict_masks=True)
        if contours is not None:
            iou_matrix = pp.compute_iou_matrix_segmentation_contours(contours, pp.convert_mask_to_binary(gt_mask).astype(np.uint8))
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_segmentation_from_iou_matrix(iou_matrix=iou_matrix)
        else:
            iou_matrix = pp.compute_iou_matrix_detection(boxes, gt_boxes)
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_detection_from_iou_matrix(iou_matrix=iou_matrix)

        print("Threshold", thres)
        print("tp, fp, fn, pq, precision, recall, f1_score, mean_iou:", tp, fp, fn, pq, precision, recall, f1_score, mean_iou)
        pq_data.append((f'{thres:4.2f}', pq, f1_score, precision, recall, mean_iou))


        fig, ax = plt.subplots(1, 1, figsize=(12*4, 12*4), dpi=200)
        plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
        plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
        plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
        plot_dir.mkdir(exist_ok=True)
        plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_{int(thres*100)}.png', dpi=200)
        plt.close('all')

    # fig, ax = plt.subplots(1, 1, figsize=(10, 10), dpi=80)
    # plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    # plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')

pq_data = pd.DataFrame(data=pq_data, columns=["thres", "pq", "f1_score", "precision", "recall", "iou"])
pq_data.to_csv(results_dir / f'test_metrics_added_eval_{str(ds)}_{ds.split}.csv', index=False)

pq_data.groupby('thres').mean()
# plot_boxes(im, boxes, format='yxyx_px')

438
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 9 5 0 0.6340950487826639 0.6428571428571429 1.0 0.782608695652174 0.8102325623334039
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 9 4 0 0.6629175510000578 0.6923076923076923 1.0 0.8181818181818181 0.8102325623334039
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 9 2 0 0.7292093061000635 0.8181818181818182 1.0 0.9 0.8102325623334039
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 9 2 0 0.7292093061000635 0.8181818181818182 1.0 0.9 0.8102325623334039
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 8 1 1 0.7174275571196396 0.8888888888888888 0.8888888888888888 0.8888888888888888 0.8071060017595946
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 8 1 1 0.7174275571196396 0.8888888888888888 0.8888888888888888 0.8888888888888888 0.8071060017595946
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 5 0 4 0.5985391915477212 1.0 0.5555555555555556 0.7142857142857143 0.8379548681668096
438
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 13 1 0.5324212119826314 0.5 0.9285714285714286 0.65 0.8191095568963559
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 11 1 0.5604433810343488 0.5416666666666666 0.9285714285714286 0.6842105263157894 0.8191095568963559
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 11 1 0.5604433810343488 0.5416666666666666 0.9285714285714286 0.6842105263157894 0.8191095568963559
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 10 2 0.5508960288782372 0.5454545454545454 0.8571428571428571 0.6666666666666665 0.8263440433173558
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 9 2 0.5666359154176154 0.5714285714285714 0.8571428571428571 0.6857142857142857 0.8263440433173558
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 9 2 0.5666359154176154 0.5714285714285714 0.8571428571428571 0.6857142857142857 0.8263440433173558
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 5 3 0.6151288442575683 0.6875 0.7857142857142857 0.7333333333333334 0.8388120603512295
438
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 15 8 0.5679135194855471 0.6341463414634146 0.7647058823529411 0.6933333333333332 0.8191060377195392
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 25 13 9 0.5689359020886221 0.6578947368421053 0.7352941176470589 0.6944444444444445 0.8192676990076159
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 11 10 0.5706344139242087 0.6857142857142857 0.7058823529411765 0.6956521739130436 0.82028697001605
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 7 12 0.5753774329924102 0.7586206896551724 0.6470588235294118 0.6984126984126984 0.8238358699664055
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 17 4 17 0.516953673809307 0.8095238095238095 0.5 0.6181818181818182 0.8362485899856438
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 2 21 0.44401031604349284 0.8666666666666667 0.38235294117647056 0.5306122448979592 0.8367886725435058
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 0 24 0.3782804800582414 1.0 0.29411764705882354 0.45454545454545453 0.8322170561281311
409
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 6 5 0 0.6570595507847579 0.5454545454545454 1.0 0.7058823529411764 0.9308343636117403
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 6 5 0 0.6570595507847579 0.5454545454545454 1.0 0.7058823529411764 0.9308343636117403
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 6 5 0 0.6570595507847579 0.5454545454545454 1.0 0.7058823529411764 0.9308343636117403
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 6 5 0 0.6570595507847579 0.5454545454545454 1.0 0.7058823529411764 0.9308343636117403
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 6 4 0 0.6981257727088053 0.6 1.0 0.7499999999999999 0.9308343636117403
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 6 3 0 0.7446674908893923 0.6666666666666666 1.0 0.8 0.9308343636117403
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 6 1 0 0.8592317202569911 0.8571428571428571 1.0 0.923076923076923 0.9308343636117403
584
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 15 14 12 0.4403611820298329 0.5172413793103449 0.5555555555555556 0.5357142857142857 0.8220075397890214
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 14 10 13 0.4523274157994807 0.5833333333333334 0.5185185185185185 0.5490196078431373 0.8238820787776255
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 6 15 0.44053462265853877 0.6666666666666666 0.4444444444444444 0.5333333333333333 0.8260024174847601
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 3 15 0.4720013814198629 0.8 0.4444444444444444 0.5714285714285714 0.8260024174847601
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 2 15 0.4835136102349816 0.8571428571428571 0.4444444444444444 0.5853658536585367 0.8260024174847601
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 1 16 0.46087992530748095 0.9166666666666666 0.4074074074074074 0.5641025641025641 0.8170144130450798
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 9 0 18 0.4237735166212976 1.0 0.3333333333333333 0.5 0.8475470332425952
525
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 6 7 0 0.5582001315620806 0.46153846153846156 1.0 0.631578947368421 0.8838168749732942
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 6 6 0 0.5892112499821961 0.5 1.0 0.6666666666666666 0.8838168749732942
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 6 6 0 0.5892112499821961 0.5 1.0 0.6666666666666666 0.8838168749732942
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 6 4 0 0.6628626562299706 0.6 1.0 0.7499999999999999 0.8838168749732942
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 6 4 0 0.6628626562299706 0.6 1.0 0.7499999999999999 0.8838168749732942
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 6 2 0 0.7575573214056808 0.75 1.0 0.8571428571428571 0.8838168749732942
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 6 0 0 0.8838168749732942 1.0 1.0 1.0 0.8838168749732942

             pq  f1_score  precision    recall       iou
thres
0.50   0.565008  0.666520   0.550206  0.874805  0.847518
0.60   0.581816  0.686401   0.586776  0.863731  0.847857
0.70   0.591182  0.697624   0.626281  0.846483  0.848380
0.80   0.607901  0.715398   0.677952  0.824774  0.850178
0.85   0.607587  0.713025   0.721164  0.781746  0.851725
0.90   0.615196  0.721077   0.776720  0.755965  0.850317
0.95   0.626462  0.720874   0.924107  0.661453  0.861864

In [9]:
ds = dl.OrganoID(split='test_Lung')
pq_data = []
for idx in range(len(ds)):
    im, gt_mask, gt_boxes, im_path, im_ID = ds[idx]
    im, flatfield = dl.normalize(im)

    H, W = im.shape[:2]
    patch_size = int(np.ceil(max(H, W) * 7 / 12))
    print(patch_size)

    contours, boxes, scores = samos.forward(im, patch_size=patch_size, predict_masks=True)
    for thres in [0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.95]:
        contours, boxes, scores = samos.set_threshold(conf_thres=thres, predict_masks=True)
        if contours is not None:
            iou_matrix = pp.compute_iou_matrix_segmentation_contours(contours, pp.convert_mask_to_binary(gt_mask).astype(np.uint8))
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_segmentation_from_iou_matrix(iou_matrix=iou_matrix)
        else:
            iou_matrix = pp.compute_iou_matrix_detection(boxes, gt_boxes)
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_detection_from_iou_matrix(iou_matrix=iou_matrix)

        print("Threshold", thres)
        print("tp, fp, fn, pq, precision, recall, f1_score, mean_iou:", tp, fp, fn, pq, precision, recall, f1_score, mean_iou)
        pq_data.append((f'{thres:4.2f}', pq, f1_score, precision, recall, mean_iou))


        fig, ax = plt.subplots(1, 1, figsize=(12*4, 12*4), dpi=200)
        plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
        plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
        plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
        plot_dir.mkdir(exist_ok=True)
        plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_{int(thres*100)}.png', dpi=200)
        plt.close('all')

    # fig, ax = plt.subplots(1, 1, figsize=(10, 10), dpi=80)
    # plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    # plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')

pq_data = pd.DataFrame(data=pq_data, columns=["thres", "pq", "f1_score", "precision", "recall", "iou"])
pq_data.to_csv(results_dir / f'test_metrics_added_eval_{str(ds)}_{ds.split}.csv', index=False)

pq_data.groupby('thres').mean()
# plot_boxes(im, boxes, format='yxyx_px')

598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 8 1 0.756671037723776 0.7333333333333333 0.9565217391304348 0.8301886792452831 0.9114446590763664
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 8 1 0.756671037723776 0.7333333333333333 0.9565217391304348 0.8301886792452831 0.9114446590763664
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 8 1 0.756671037723776 0.7333333333333333 0.9565217391304348 0.8301886792452831 0.9114446590763664
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 8 1 0.756671037723776 0.7333333333333333 0.9565217391304348 0.8301886792452831 0.9114446590763664
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 8 2 0.7343717363590881 0.7241379310344828 0.9130434782608695 0.8076923076923076 0.9092221497779187
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 8 2 0.7343717363590881 0.7241379310344828 0.9130434782608695 0.8076923076923076 0.9092221497779187
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 2 0.7637466058134517 0.7777777777777778 0.9130434782608695 0.84 0.9092221497779187
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 61 9 1 0.8667868612848674 0.8714285714285714 0.9838709677419355 0.9242424242424242 0.937834964668873
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 61 9 1 0.8606049682497297 0.8714285714285714 0.9838709677419355 0.9242424242424242 0.9311463590898715
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 61 9 1 0.8606049682497297 0.8714285714285714 0.9838709677419355 0.9242424242424242 0.9311463590898715
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 61 8 1 0.8672251046727643 0.8840579710144928 0.9838709677419355 0.9312977099236642 0.9312007271486239
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 61 8 1 0.8672251046727643 0.8840579710144928 0.9838709677419355 0.9312977099236642 0.9312007271486239
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 58 5 4 0.8646719643865812 0.9206349206349206 0.9354838709677419 0.9279999999999999 0.9317585823131262
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 2 9 0.8475935191483011 0.9636363636363636 0.8548387096774194 0.905982905982906 0.9355513371731248
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 45 12 0 0.7926753399261761 0.7894736842105263 1.0 0.8823529411764706 0.8983653852496664
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 45 10 0 0.8085288467246997 0.8181818181818182 1.0 0.9 0.8983653852496664
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 45 9 0 0.816695804772424 0.8333333333333334 1.0 0.9090909090909091 0.8983653852496664
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 45 7 0 0.8335348935306183 0.8653846153846154 1.0 0.9278350515463918 0.8983653852496664
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 45 7 0 0.8335348935306183 0.8653846153846154 1.0 0.9278350515463918 0.8983653852496664
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 44 7 1 0.8222413581953717 0.8627450980392157 0.9777777777777777 0.9166666666666665 0.8969905725767692
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 41 4 4 0.8191100111096975 0.9111111111111111 0.9111111111111111 0.9111111111111111 0.8990231829252777
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 35 16 0 0.711627756005653 0.6862745098039216 1.0 0.813953488372093 0.8742855288069451
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 34 13 1 0.7326874364829972 0.723404255319149 0.9714285714285714 0.8292682926829269 0.8835348498765554
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 34 10 1 0.7605110100203262 0.7727272727272727 0.9714285714285714 0.8607594936708862 0.8835348498765554
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 34 8 1 0.7802645427481268 0.8095238095238095 0.9714285714285714 0.8831168831168832 0.8835348498765554
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 34 8 1 0.7802645427481268 0.8095238095238095 0.9714285714285714 0.8831168831168832 0.8835348498765554
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 34 6 1 0.8010715972214103 0.85 0.9714285714285714 0.9066666666666667 0.8835348498765554
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 34 4 1 0.8230187642685721 0.8947368421052632 0.9714285714285714 0.9315068493150684 0.8835348498765554
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 34 15 1 0.7197914732651686 0.6938775510204082 0.9714285714285714 0.8095238095238094 0.889154172856973
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 33 12 2 0.7408675022598391 0.7333333333333333 0.9428571428571428 0.8250000000000001 0.8980212148604111
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 33 11 2 0.7502455719086979 0.75 0.9428571428571428 0.8354430379746834 0.8980212148604111
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 33 10 2 0.7598641048818863 0.7674418604651163 0.9428571428571428 0.8461538461538461 0.8980212148604111
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 33 7 2 0.7902586690771617 0.825 0.9428571428571428 0.88 0.8980212148604111
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 33 6 2 0.8009378402809072 0.8461538461538461 0.9428571428571428 0.8918918918918919 0.8980212148604111
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 30 4 5 0.8003379625514376 0.8823529411764706 0.8571428571428571 0.8695652173913043 0.9203886569341532
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 14 0 0.592986032426461 0.5333333333333333 1.0 0.6956521739130436 0.8524174216130376
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 13 0 0.6061634998137156 0.5517241379310345 1.0 0.7111111111111111 0.8524174216130376
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 13 0 0.6061634998137156 0.5517241379310345 1.0 0.7111111111111111 0.8524174216130376
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 10 0 0.6494608926575525 0.6153846153846154 1.0 0.761904761904762 0.8524174216130376
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 9 0 0.6653014022345659 0.64 1.0 0.7804878048780487 0.8524174216130376
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 6 0 0.7178251971478211 0.7272727272727273 1.0 0.8421052631578948 0.8524174216130376
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 2 0 0.8022752203416824 0.8888888888888888 1.0 0.9411764705882353 0.8524174216130376

             pq  f1_score  precision    recall       iou
thres
0.50   0.740090  0.825986   0.717953  0.985304  0.893917
0.60   0.750921  0.836635   0.738568  0.975780  0.895822
0.70   0.758482  0.845139   0.752091  0.975780  0.895822
0.80   0.774503  0.863416   0.779188  0.975780  0.895831
0.85   0.778493  0.868405   0.791351  0.968533  0.895460
0.90   0.790187  0.882170   0.821824  0.956765  0.895324
0.95   0.809347  0.899890   0.886417  0.917927  0.900023

In [10]:
ds = dl.OrganoID(split='test_C')
pq_data = []
for idx in range(len(ds)):
    im, gt_mask, gt_boxes, im_path, im_ID = ds[idx]
    im, flatfield = dl.normalize(im)

    H, W = im.shape[:2]
    patch_size = int(np.ceil(max(H, W) * 7 / 12))
    print(patch_size)

    contours, boxes, scores = samos.forward(im, patch_size=patch_size, predict_masks=True)
    for thres in [0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.95]:
        contours, boxes, scores = samos.set_threshold(conf_thres=thres, predict_masks=True)
        if contours is not None:
            iou_matrix = pp.compute_iou_matrix_segmentation_contours(contours, pp.convert_mask_to_binary(gt_mask).astype(np.uint8))
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_segmentation_from_iou_matrix(iou_matrix=iou_matrix)
        else:
            iou_matrix = pp.compute_iou_matrix_detection(boxes, gt_boxes)
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_detection_from_iou_matrix(iou_matrix=iou_matrix)

        print("Threshold", thres)
        print("tp, fp, fn, pq, precision, recall, f1_score, mean_iou:", tp, fp, fn, pq, precision, recall, f1_score, mean_iou)
        pq_data.append((f'{thres:4.2f}', pq, f1_score, precision, recall, mean_iou))


        fig, ax = plt.subplots(1, 1, figsize=(12*4, 12*4), dpi=200)
        plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
        plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
        plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
        plot_dir.mkdir(exist_ok=True)
        plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_{int(thres*100)}.png', dpi=200)
        plt.close('all')

    # fig, ax = plt.subplots(1, 1, figsize=(10, 10), dpi=80)
    # plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    # plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')

pq_data = pd.DataFrame(data=pq_data, columns=["thres", "pq", "f1_score", "precision", "recall", "iou"])
pq_data.to_csv(results_dir / f'test_metrics_added_eval_{str(ds)}_{ds.split}.csv', index=False)

pq_data.groupby('thres').mean()
# plot_boxes(im, boxes, format='yxyx_px')

598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 22 4 0.47320248346730276 0.42105263157894735 0.8 0.5517241379310345 0.8576795012844862
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 19 4 0.4990135280200647 0.45714285714285713 0.8 0.5818181818181818 0.8576795012844862
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 17 4 0.5178442271906332 0.48484848484848486 0.8 0.6037735849056605 0.8576795012844862
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 15 4 0.538151843943207 0.5161290322580645 0.8 0.6274509803921569 0.8576795012844862
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 16 12 4 0.5717863341896575 0.5714285714285714 0.8 0.6666666666666666 0.8576795012844862
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 14 10 6 0.5552674476706448 0.5833333333333334 0.7 0.6363636363636365 0.8725631320538705
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 14 5 6 0.6264555819873942 0.7368421052631579 0.7 0.717948717948718 0.8725631320538705
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 15 34 1 0.3749420678179223 0.30612244897959184 0.9375 0.46153846153846156 0.812374480272165
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 15 32 1 0.3861851761893647 0.3191489361702128 0.9375 0.4761904761904763 0.8109888699976658
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 15 26 1 0.42683624736719256 0.36585365853658536 0.9375 0.5263157894736842 0.8109888699976658
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 15 20 1 0.4770522764692152 0.42857142857142855 0.9375 0.588235294117647 0.8109888699976658
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 15 17 1 0.5068680437485412 0.46875 0.9375 0.625 0.8109888699976658
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 14 13 2 0.530187027169908 0.5185185185185185 0.875 0.6511627906976744 0.8142157917252159
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 14 8 2 0.599948478113317 0.6363636363636364 0.875 0.7368421052631579 0.8142157917252159
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 24 2 0.5774347892317565 0.5 0.9230769230769231 0.6486486486486487 0.8902119667322913
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 18 2 0.6286686547231247 0.5714285714285714 0.9230769230769231 0.7058823529411765 0.8906139275244267
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 15 2 0.6576841310949613 0.6153846153846154 0.9230769230769231 0.7384615384615384 0.8906139275244267
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 12 3 0.6731804685331091 0.6571428571428571 0.8846153846153846 0.7540983606557377 0.892695838706949
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 9 3 0.708000147939994 0.71875 0.8846153846153846 0.7931034482758621 0.892695838706949
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 6 3 0.7466183378276301 0.7931034482758621 0.8846153846153846 0.8363636363636363 0.892695838706949
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 3 4 0.7693896464411333 0.88 0.8461538461538461 0.8627450980392156 0.8917925447385863
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 25 0 0.37815992937142595 0.2857142857142857 1.0 0.4444444444444445 0.8508598410857084
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 9 20 1 0.3971940923789553 0.3103448275862069 0.9 0.4615384615384615 0.8605872001544032
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 9 13 1 0.4802164738546045 0.4090909090909091 0.9 0.5625000000000001 0.8537181757415191
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 9 12 1 0.4966815739854507 0.42857142857142855 0.9 0.5806451612903225 0.8553960440860541
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 9 10 1 0.5309354756396197 0.47368421052631576 0.9 0.6206896551724138 0.8553960440860541
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 9 7 1 0.5921972612903451 0.5625 0.9 0.6923076923076923 0.8553960440860541
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 9 4 1 0.6694403823282162 0.6923076923076923 0.9 0.7826086956521738 0.8553960440860541
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 17 3 0.4909899486685738 0.43333333333333335 0.8125 0.5652173913043479 0.8686745245674767
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 16 3 0.5019008364167643 0.4482758620689655 0.8125 0.5777777777777777 0.8686745245674767
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 14 3 0.5252450613663813 0.48148148148148145 0.8125 0.6046511627906976 0.8686745245674767
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 12 10 4 0.5573406376884471 0.5454545454545454 0.75 0.631578947368421 0.8824560096733746
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 8 5 0.5533606707841146 0.5789473684210527 0.6875 0.6285714285714286 0.8803465217020005
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 11 7 5 0.5696359846307062 0.6111111111111112 0.6875 0.6470588235294118 0.8803465217020005
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 10 3 6 0.6213995829076373 0.7692307692307693 0.625 0.6896551724137931 0.9010293952160741
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 27 0 0.4085066347376756 0.325 1.0 0.4905660377358491 0.832725063119108
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 24 0 0.43301703282193615 0.35135135135135137 1.0 0.52 0.832725063119108
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 15 0 0.5280695522218734 0.4642857142857143 1.0 0.6341463414634146 0.832725063119108
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 9 0 0.6185957611741945 0.5909090909090909 1.0 0.7428571428571429 0.832725063119108
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 8 0 0.6367897541499061 0.6190476190476191 1.0 0.7647058823529412 0.832725063119108
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 5 0 0.698414569067639 0.7222222222222222 1.0 0.8387096774193548 0.832725063119108
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 13 5 0 0.698414569067639 0.7222222222222222 1.0 0.8387096774193548 0.832725063119108

             pq  f1_score  precision    recall       iou
thres
0.50   0.450539  0.527023   0.378537  0.912179  0.852088
0.60   0.474330  0.553868   0.409615  0.895513  0.853545
0.70   0.522649  0.611641   0.470157  0.895513  0.852400
0.80   0.560167  0.654144   0.527796  0.878686  0.855324
0.85   0.584623  0.683123   0.571768  0.868269  0.854972
0.90   0.615387  0.716994   0.631798  0.841186  0.857990
0.95   0.664175  0.771418   0.739494  0.824359  0.861287

## OrgaSegment

In [ ]:
ds = dl.OrgaSegment(split='test')
pq_data = []
for idx in range(len(ds)):
    im, gt_mask, gt_boxes, im_path, im_ID = ds[idx]
    im, flatfield = dl.normalize(im)

    H, W = im.shape[:2]
    # patch_size = int(np.ceil(max(H, W) * 7 / 12))
    patch_size = 512
    print(patch_size)

    contours, boxes, scores = samos.forward(im, patch_size=patch_size, predict_masks=True)
    for thres in [0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.95]:
        contours, boxes, scores = samos.set_threshold(conf_thres=thres, predict_masks=True)
        if contours is not None:
            iou_matrix = pp.compute_iou_matrix_segmentation_contours(contours, pp.convert_mask_to_binary(gt_mask).astype(np.uint8))
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_segmentation_from_iou_matrix(iou_matrix=iou_matrix)
        else:
            iou_matrix = pp.compute_iou_matrix_detection(boxes, gt_boxes)
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_detection_from_iou_matrix(iou_matrix=iou_matrix)

        print("Threshold", thres)
        print("tp, fp, fn, pq, precision, recall, f1_score, mean_iou:", tp, fp, fn, pq, precision, recall, f1_score, mean_iou)
        pq_data.append((f'{thres:4.2f}', pq, f1_score, precision, recall, mean_iou))


        fig, ax = plt.subplots(1, 1, figsize=(12*4, 12*4), dpi=200)
        plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
        plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
        plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
        plot_dir.mkdir(exist_ok=True)
        plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_{int(thres*100)}.png', dpi=200)
        plt.close('all')

    # fig, ax = plt.subplots(1, 1, figsize=(10, 10), dpi=80)
    # plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    # plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')

pq_data = pd.DataFrame(data=pq_data, columns=["thres", "pq", "f1_score", "precision", "recall", "iou"])
pq_data.to_csv(results_dir / f'test_metrics_added_eval_{str(ds)}_{ds.split}.csv', index=False)

pq_data.groupby('thres').mean()
# plot_boxes(im, boxes, format='yxyx_px')

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

976
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 64 107 116 0.2758711760212687 0.3742690058479532 0.35555555555555557 0.36467236467236464 0.7564904904958228
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 61 89 119 0.2815202601479259 0.4066666666666667 0.3388888888888889 0.36969696969696975 0.76148922826898
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 59 71 121 0.2911250693925507 0.45384615384615384 0.3277777777777778 0.3806451612903226 0.7648200975567009
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 52 125 0.2994225568747437 0.514018691588785 0.3055555555555556 0.3832752613240418 0.7812206711186493
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 50 44 130 0.2875695909761604 0.5319148936170213 0.2777777777777778 0.36496350364963503 0.7879406792746795
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 43 36 137 0.26428264165667786 0.5443037974683544 0.2388888888888889 0.33204633204633205 0.7959209789427857
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 36 14 144 0.2562414522999078 0.72 0.2 0.3130434782608696 0.8185490837358166
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 70 66 9 0.5603459999469422 0.5147058823529411 0.8860759493670886 0.6511627906976745 0.8605313570613755
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 69 56 10 0.5823724411939895 0.552 0.8734177215189873 0.6764705882352942 0.8608983913302453
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 67 45 12 0.6055967370489593 0.5982142857142857 0.8481012658227848 0.7015706806282722 0.8632013192265017
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 37 13 0.626391605762669 0.6407766990291263 0.8354430379746836 0.7252747252747253 0.8636611534000435
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 28 13 0.6589784523052356 0.7021276595744681 0.8354430379746836 0.7630057803468209 0.8636611534000435
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 18 13 0.6994065782135321 0.7857142857142857 0.8354430379746836 0.8098159509202455 0.8636611534000435
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 7 24 0.6864309603135166 0.8870967741935484 0.6962025316455697 0.7801418439716311 0.8798796854927804
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 52 1 0.5549220504662298 0.5047619047619047 0.9814814814814815 0.6666666666666667 0.8323830756993447
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 41 1 0.5961662569198009 0.5638297872340425 0.9814814814814815 0.7162162162162162 0.8323830756993447
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 36 1 0.6170112309379757 0.5955056179775281 0.9814814814814815 0.7412587412587414 0.8323830756993447
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 25 2 0.6608268725942352 0.6753246753246753 0.9629629629629629 0.7938931297709924 0.8323876952869694
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 19 2 0.6925465624787586 0.7323943661971831 0.9629629629629629 0.832 0.8323876952869694
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 13 2 0.7274648765533178 0.8 0.9629629629629629 0.8739495798319328 0.8323876952869694
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 51 4 3 0.7797770575668476 0.9272727272727272 0.9444444444444444 0.9357798165137615 0.8332911693606508
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 68 3 0.30184866483914596 0.25274725274725274 0.8846153846153846 0.39316239316239315 0.7677455170908712
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 53 3 0.3462381743743145 0.3026315789473684 0.8846153846153846 0.45098039215686275 0.7677455170908712
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 43 3 0.3838727585454356 0.3484848484848485 0.8846153846153846 0.5 0.7677455170908712
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 36 4 0.40668742632222576 0.3793103448275862 0.8461538461538461 0.5238095238095238 0.7764032684333401
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 31 4 0.4324271368489489 0.41509433962264153 0.8461538461538461 0.5569620253164558 0.7764032684333401
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 23 5 0.4612904089758796 0.4772727272727273 0.8076923076923077 0.6000000000000001 0.7688173482931326
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 15 6 0.501544578192486 0.5714285714285714 0.7692307692307693 0.6557377049180327 0.7648554817435411
438
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 20 0 0.5731665590343088 0.5238095238095238 1.0 0.6875000000000001 0.8336968131408128
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 13 1 0.6274894139828582 0.6176470588235294 0.9545454545454546 0.75 0.8366525519771442
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 11 1 0.6507297626488899 0.65625 0.9545454545454546 0.7777777777777778 0.8366525519771442
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 10 1 0.663007682698869 0.6774193548387096 0.9545454545454546 0.7924528301886793 0.8366525519771442
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 10 1 0.663007682698869 0.6774193548387096 0.9545454545454546 0.7924528301886793 0.8366525519771442
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 8 1 0.6890079839811776 0.7241379310344828 0.9545454545454546 0.823529411764706 0.8366525519771442
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 5 3 0.6917586131069555 0.7916666666666666 0.8636363636363636 0.8260869565217391 0.8373920053399988
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 41 1 0.44710161046040403 0.3880597014925373 0.9629629629629629 0.553191489361702 0.808222141986115
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 35 1 0.47758581117361343 0.4262295081967213 0.9629629629629629 0.5909090909090909 0.808222141986115
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 27 1 0.5205965533357929 0.49056603773584906 0.9629629629629629 0.65 0.8009177743627584
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 20 1 0.5705167707789511 0.5652173913043478 0.9629629629629629 0.7123287671232876 0.8009177743627584
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 17 3 0.5728935651202653 0.5853658536585366 0.8888888888888888 0.7058823529411764 0.8115992172537093
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 14 4 0.5813049324208015 0.6216216216216216 0.8518518518518519 0.7187499999999999 0.8087720798898108
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 6 0.6152196467652105 0.7777777777777778 0.7777777777777778 0.7777777777777778 0.7909966886981278
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 12 10 0.5697235213427492 0.6571428571428571 0.696969696969697 0.676470588235294 0.84219998807189
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 10 10 0.5869878704743475 0.696969696969697 0.696969696969697 0.696969696969697 0.84219998807189
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 7 12 0.594053957464425 0.75 0.6363636363636364 0.6885245901639345 0.8627926525078554
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 12 0.6039548567554988 0.7777777777777778 0.6363636363636364 0.7000000000000001 0.8627926525078554
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 4 12 0.6247808862987918 0.84 0.6363636363636364 0.7241379310344828 0.8627926525078554
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 4 13 0.6069781845896316 0.8333333333333334 0.6060606060606061 0.7017543859649124 0.864943913040225
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 2 15 0.5888948931389513 0.9 0.5454545454545454 0.679245283018868 0.8669841482323448
299
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 14 9 0.5551036051470244 0.6744186046511628 0.7631578947368421 0.7160493827160495 0.7752308968432582
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 11 9 0.5764537438065254 0.725 0.7631578947368421 0.7435897435897436 0.7752308968432582
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 7 9 0.6076134056339051 0.8055555555555556 0.7631578947368421 0.7837837837837838 0.7752308968432582
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 6 12 0.5835012734716382 0.8125 0.6842105263157895 0.742857142857143 0.7854824835195129
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 5 14 0.5684434639797412 0.8275862068965517 0.631578947368421 0.716417910447761 0.7934523351383888
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 3 14 0.5859340321021947 0.8888888888888888 0.631578947368421 0.7384615384615385 0.7934523351383888
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 1 19 0.5271950472390986 0.95 0.5 0.6551724137931034 0.8046661247333611
613
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 47 60 4 0.48535025865836007 0.4392523364485981 0.9215686274509803 0.5949367088607594 0.8158014985959668
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 47 52 4 0.5112356057868059 0.47474747474747475 0.9215686274509803 0.6266666666666666 0.8158014985959668
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 46 44 5 0.5294134542310958 0.5111111111111111 0.9019607843137255 0.652482269503546 0.8113836635498315
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 44 28 7 0.5812565791658437 0.6111111111111112 0.8627450980392157 0.7154471544715448 0.8124381731522589
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 43 28 8 0.574963941836602 0.6056338028169014 0.8431372549019608 0.7049180327868853 0.8156465221402959
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 39 16 12 0.5953074972408575 0.7090909090909091 0.7647058823529411 0.7358490566037736 0.8090076244555243
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 34 7 17 0.6006003304950215 0.8292682926829268 0.6666666666666666 0.7391304347826086 0.8125769177285586
1195
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 89 64 24 0.5484881967555755 0.5816993464052288 0.7876106194690266 0.6691729323308271 0.8196509007695679
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 88 54 25 0.5674150244395908 0.6197183098591549 0.7787610619469026 0.6901960784313725 0.8221069956369071
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 87 42 26 0.5904155415931948 0.6744186046511628 0.7699115044247787 0.71900826446281 0.8211526498020295
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 80 33 33 0.5910453025983493 0.7079646017699115 0.7079646017699115 0.7079646017699115 0.8348514899201683
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 75 25 38 0.5909939687752785 0.75 0.6637168141592921 0.7042253521126761 0.8392114356608956
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 71 16 42 0.5988852665747906 0.8160919540229885 0.6283185840707964 0.71 0.8435003754574516
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 62 7 51 0.5770305717405755 0.8985507246376812 0.5486725663716814 0.6813186813186812 0.8469319681998769

             pq  f1_score  precision    recall       iou
thres
0.50   0.487192  0.597299   0.491087  0.824000  0.811195
0.60   0.515346  0.631170   0.538544  0.815637  0.812273
0.70   0.539043  0.659505   0.588395  0.803088  0.813628
0.80   0.558661  0.679730   0.636142  0.775891  0.818681
0.85   0.566661  0.686497   0.666754  0.754057  0.821975
0.90   0.580986  0.704416   0.720046  0.728205  0.821712
0.95   0.582469  0.704343   0.825306  0.651209  0.825612

## OrgaQuant

In [ ]:
ds = dl.OrgaQuant(split='test')
pq_data = []
for idx in range(len(ds)):
    im, gt_mask, gt_boxes, im_path, im_ID = ds[idx]
    im, flatfield = dl.normalize(im)

    H, W = im.shape[:2]
    # patch_size = int(np.ceil(max(H, W) * 7 / 12))
    patch_size = 512
    print(patch_size)

    contours, boxes, scores = samos.forward(im, patch_size=patch_size, predict_masks=True)
    for thres in [0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.95]:
        contours, boxes, scores = samos.set_threshold(conf_thres=thres, predict_masks=True)
        if contours is not None:
            iou_matrix = pp.compute_iou_matrix_segmentation_contours(contours, pp.convert_mask_to_binary(gt_mask).astype(np.uint8))
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_segmentation_from_iou_matrix(iou_matrix=iou_matrix)
        else:
            iou_matrix = pp.compute_iou_matrix_detection(boxes, gt_boxes)
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_detection_from_iou_matrix(iou_matrix=iou_matrix)

        print("Threshold", thres)
        print("tp, fp, fn, pq, precision, recall, f1_score, mean_iou:", tp, fp, fn, pq, precision, recall, f1_score, mean_iou)
        pq_data.append((f'{thres:4.2f}', pq, f1_score, precision, recall, mean_iou))


        fig, ax = plt.subplots(1, 1, figsize=(12*4, 12*4), dpi=200)
        plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
        plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
        plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
        plot_dir.mkdir(exist_ok=True)
        plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_{int(thres*100)}.png', dpi=200)
        plt.close('all')

    # fig, ax = plt.subplots(1, 1, figsize=(10, 10), dpi=80)
    # plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    # plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')

pq_data = pd.DataFrame(data=pq_data, columns=["thres", "pq", "f1_score", "precision", "recall", "iou"])
pq_data.to_csv(results_dir / f'test_metrics_added_eval_{str(ds)}_{ds.split}.csv', index=False)

pq_data.groupby('thres').mean()
# plot_boxes(im, boxes, format='yxyx_px')

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

976
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 64 107 116 0.2758711760212687 0.3742690058479532 0.35555555555555557 0.36467236467236464 0.7564904904958228
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 61 89 119 0.2815202601479259 0.4066666666666667 0.3388888888888889 0.36969696969696975 0.76148922826898
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 59 71 121 0.2911250693925507 0.45384615384615384 0.3277777777777778 0.3806451612903226 0.7648200975567009
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 52 125 0.2994225568747437 0.514018691588785 0.3055555555555556 0.3832752613240418 0.7812206711186493
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 50 44 130 0.2875695909761604 0.5319148936170213 0.2777777777777778 0.36496350364963503 0.7879406792746795
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 43 36 137 0.26428264165667786 0.5443037974683544 0.2388888888888889 0.33204633204633205 0.7959209789427857
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 36 14 144 0.2562414522999078 0.72 0.2 0.3130434782608696 0.8185490837358166
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 70 66 9 0.5603459999469422 0.5147058823529411 0.8860759493670886 0.6511627906976745 0.8605313570613755
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 69 56 10 0.5823724411939895 0.552 0.8734177215189873 0.6764705882352942 0.8608983913302453
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 67 45 12 0.6055967370489593 0.5982142857142857 0.8481012658227848 0.7015706806282722 0.8632013192265017
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 37 13 0.626391605762669 0.6407766990291263 0.8354430379746836 0.7252747252747253 0.8636611534000435
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 28 13 0.6589784523052356 0.7021276595744681 0.8354430379746836 0.7630057803468209 0.8636611534000435
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 18 13 0.6994065782135321 0.7857142857142857 0.8354430379746836 0.8098159509202455 0.8636611534000435
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 7 24 0.6864309603135166 0.8870967741935484 0.6962025316455697 0.7801418439716311 0.8798796854927804
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 52 1 0.5549220504662298 0.5047619047619047 0.9814814814814815 0.6666666666666667 0.8323830756993447
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 41 1 0.5961662569198009 0.5638297872340425 0.9814814814814815 0.7162162162162162 0.8323830756993447
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 36 1 0.6170112309379757 0.5955056179775281 0.9814814814814815 0.7412587412587414 0.8323830756993447
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 25 2 0.6608268725942352 0.6753246753246753 0.9629629629629629 0.7938931297709924 0.8323876952869694
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 19 2 0.6925465624787586 0.7323943661971831 0.9629629629629629 0.832 0.8323876952869694
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 13 2 0.7274648765533178 0.8 0.9629629629629629 0.8739495798319328 0.8323876952869694
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 51 4 3 0.7797770575668476 0.9272727272727272 0.9444444444444444 0.9357798165137615 0.8332911693606508
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 68 3 0.30184866483914596 0.25274725274725274 0.8846153846153846 0.39316239316239315 0.7677455170908712
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 53 3 0.3462381743743145 0.3026315789473684 0.8846153846153846 0.45098039215686275 0.7677455170908712
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 43 3 0.3838727585454356 0.3484848484848485 0.8846153846153846 0.5 0.7677455170908712
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 36 4 0.40668742632222576 0.3793103448275862 0.8461538461538461 0.5238095238095238 0.7764032684333401
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 31 4 0.4324271368489489 0.41509433962264153 0.8461538461538461 0.5569620253164558 0.7764032684333401
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 23 5 0.4612904089758796 0.4772727272727273 0.8076923076923077 0.6000000000000001 0.7688173482931326
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 15 6 0.501544578192486 0.5714285714285714 0.7692307692307693 0.6557377049180327 0.7648554817435411
438
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 20 0 0.5731665590343088 0.5238095238095238 1.0 0.6875000000000001 0.8336968131408128
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 13 1 0.6274894139828582 0.6176470588235294 0.9545454545454546 0.75 0.8366525519771442
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 11 1 0.6507297626488899 0.65625 0.9545454545454546 0.7777777777777778 0.8366525519771442
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 10 1 0.663007682698869 0.6774193548387096 0.9545454545454546 0.7924528301886793 0.8366525519771442
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 10 1 0.663007682698869 0.6774193548387096 0.9545454545454546 0.7924528301886793 0.8366525519771442
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 8 1 0.6890079839811776 0.7241379310344828 0.9545454545454546 0.823529411764706 0.8366525519771442
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 5 3 0.6917586131069555 0.7916666666666666 0.8636363636363636 0.8260869565217391 0.8373920053399988
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 41 1 0.44710161046040403 0.3880597014925373 0.9629629629629629 0.553191489361702 0.808222141986115
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 35 1 0.47758581117361343 0.4262295081967213 0.9629629629629629 0.5909090909090909 0.808222141986115
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 27 1 0.5205965533357929 0.49056603773584906 0.9629629629629629 0.65 0.8009177743627584
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 20 1 0.5705167707789511 0.5652173913043478 0.9629629629629629 0.7123287671232876 0.8009177743627584
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 17 3 0.5728935651202653 0.5853658536585366 0.8888888888888888 0.7058823529411764 0.8115992172537093
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 14 4 0.5813049324208015 0.6216216216216216 0.8518518518518519 0.7187499999999999 0.8087720798898108
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 6 0.6152196467652105 0.7777777777777778 0.7777777777777778 0.7777777777777778 0.7909966886981278
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 12 10 0.5697235213427492 0.6571428571428571 0.696969696969697 0.676470588235294 0.84219998807189
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 10 10 0.5869878704743475 0.696969696969697 0.696969696969697 0.696969696969697 0.84219998807189
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 7 12 0.594053957464425 0.75 0.6363636363636364 0.6885245901639345 0.8627926525078554
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 12 0.6039548567554988 0.7777777777777778 0.6363636363636364 0.7000000000000001 0.8627926525078554
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 4 12 0.6247808862987918 0.84 0.6363636363636364 0.7241379310344828 0.8627926525078554
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 4 13 0.6069781845896316 0.8333333333333334 0.6060606060606061 0.7017543859649124 0.864943913040225
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 2 15 0.5888948931389513 0.9 0.5454545454545454 0.679245283018868 0.8669841482323448
299
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 14 9 0.5551036051470244 0.6744186046511628 0.7631578947368421 0.7160493827160495 0.7752308968432582
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 11 9 0.5764537438065254 0.725 0.7631578947368421 0.7435897435897436 0.7752308968432582
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 7 9 0.6076134056339051 0.8055555555555556 0.7631578947368421 0.7837837837837838 0.7752308968432582
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 6 12 0.5835012734716382 0.8125 0.6842105263157895 0.742857142857143 0.7854824835195129
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 5 14 0.5684434639797412 0.8275862068965517 0.631578947368421 0.716417910447761 0.7934523351383888
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 3 14 0.5859340321021947 0.8888888888888888 0.631578947368421 0.7384615384615385 0.7934523351383888
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 1 19 0.5271950472390986 0.95 0.5 0.6551724137931034 0.8046661247333611
613
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 47 60 4 0.48535025865836007 0.4392523364485981 0.9215686274509803 0.5949367088607594 0.8158014985959668
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 47 52 4 0.5112356057868059 0.47474747474747475 0.9215686274509803 0.6266666666666666 0.8158014985959668
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 46 44 5 0.5294134542310958 0.5111111111111111 0.9019607843137255 0.652482269503546 0.8113836635498315
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 44 28 7 0.5812565791658437 0.6111111111111112 0.8627450980392157 0.7154471544715448 0.8124381731522589
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 43 28 8 0.574963941836602 0.6056338028169014 0.8431372549019608 0.7049180327868853 0.8156465221402959
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 39 16 12 0.5953074972408575 0.7090909090909091 0.7647058823529411 0.7358490566037736 0.8090076244555243
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 34 7 17 0.6006003304950215 0.8292682926829268 0.6666666666666666 0.7391304347826086 0.8125769177285586
1195
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 89 64 24 0.5484881967555755 0.5816993464052288 0.7876106194690266 0.6691729323308271 0.8196509007695679
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 88 54 25 0.5674150244395908 0.6197183098591549 0.7787610619469026 0.6901960784313725 0.8221069956369071
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 87 42 26 0.5904155415931948 0.6744186046511628 0.7699115044247787 0.71900826446281 0.8211526498020295
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 80 33 33 0.5910453025983493 0.7079646017699115 0.7079646017699115 0.7079646017699115 0.8348514899201683
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 75 25 38 0.5909939687752785 0.75 0.6637168141592921 0.7042253521126761 0.8392114356608956
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 71 16 42 0.5988852665747906 0.8160919540229885 0.6283185840707964 0.71 0.8435003754574516
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 62 7 51 0.5770305717405755 0.8985507246376812 0.5486725663716814 0.6813186813186812 0.8469319681998769

             pq  f1_score  precision    recall       iou
thres
0.50   0.487192  0.597299   0.491087  0.824000  0.811195
0.60   0.515346  0.631170   0.538544  0.815637  0.812273
0.70   0.539043  0.659505   0.588395  0.803088  0.813628
0.80   0.558661  0.679730   0.636142  0.775891  0.818681
0.85   0.566661  0.686497   0.666754  0.754057  0.821975
0.90   0.580986  0.704416   0.720046  0.728205  0.821712
0.95   0.582469  0.704343   0.825306  0.651209  0.825612

## OrgaExtractor

In [ ]:
ds = dl.OrgaExtractor(split='test')
pq_data = []
for idx in range(len(ds)):
    im, gt_mask, gt_boxes, im_path, im_ID = ds[idx]
    im, flatfield = dl.normalize(im)

    H, W = im.shape[:2]
    # patch_size = int(np.ceil(max(H, W) * 7 / 12))
    patch_size = 512
    print(patch_size)

    contours, boxes, scores = samos.forward(im, patch_size=patch_size, predict_masks=True)
    for thres in [0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.95]:
        contours, boxes, scores = samos.set_threshold(conf_thres=thres, predict_masks=True)
        if contours is not None:
            iou_matrix = pp.compute_iou_matrix_segmentation_contours(contours, pp.convert_mask_to_binary(gt_mask).astype(np.uint8))
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_segmentation_from_iou_matrix(iou_matrix=iou_matrix)
        else:
            iou_matrix = pp.compute_iou_matrix_detection(boxes, gt_boxes)
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_detection_from_iou_matrix(iou_matrix=iou_matrix)

        print("Threshold", thres)
        print("tp, fp, fn, pq, precision, recall, f1_score, mean_iou:", tp, fp, fn, pq, precision, recall, f1_score, mean_iou)
        pq_data.append((f'{thres:4.2f}', pq, f1_score, precision, recall, mean_iou))


        fig, ax = plt.subplots(1, 1, figsize=(12*4, 12*4), dpi=200)
        plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
        plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
        plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
        plot_dir.mkdir(exist_ok=True)
        plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_{int(thres*100)}.png', dpi=200)
        plt.close('all')

    # fig, ax = plt.subplots(1, 1, figsize=(10, 10), dpi=80)
    # plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    # plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')

pq_data = pd.DataFrame(data=pq_data, columns=["thres", "pq", "f1_score", "precision", "recall", "iou"])
pq_data.to_csv(results_dir / f'test_metrics_added_eval_{str(ds)}_{ds.split}.csv', index=False)

pq_data.groupby('thres').mean()
# plot_boxes(im, boxes, format='yxyx_px')

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

976
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 64 107 116 0.2758711760212687 0.3742690058479532 0.35555555555555557 0.36467236467236464 0.7564904904958228
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 61 89 119 0.2815202601479259 0.4066666666666667 0.3388888888888889 0.36969696969696975 0.76148922826898
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 59 71 121 0.2911250693925507 0.45384615384615384 0.3277777777777778 0.3806451612903226 0.7648200975567009
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 52 125 0.2994225568747437 0.514018691588785 0.3055555555555556 0.3832752613240418 0.7812206711186493
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 50 44 130 0.2875695909761604 0.5319148936170213 0.2777777777777778 0.36496350364963503 0.7879406792746795
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 43 36 137 0.26428264165667786 0.5443037974683544 0.2388888888888889 0.33204633204633205 0.7959209789427857
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 36 14 144 0.2562414522999078 0.72 0.2 0.3130434782608696 0.8185490837358166
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 70 66 9 0.5603459999469422 0.5147058823529411 0.8860759493670886 0.6511627906976745 0.8605313570613755
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 69 56 10 0.5823724411939895 0.552 0.8734177215189873 0.6764705882352942 0.8608983913302453
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 67 45 12 0.6055967370489593 0.5982142857142857 0.8481012658227848 0.7015706806282722 0.8632013192265017
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 37 13 0.626391605762669 0.6407766990291263 0.8354430379746836 0.7252747252747253 0.8636611534000435
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 28 13 0.6589784523052356 0.7021276595744681 0.8354430379746836 0.7630057803468209 0.8636611534000435
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 18 13 0.6994065782135321 0.7857142857142857 0.8354430379746836 0.8098159509202455 0.8636611534000435
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 7 24 0.6864309603135166 0.8870967741935484 0.6962025316455697 0.7801418439716311 0.8798796854927804
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 52 1 0.5549220504662298 0.5047619047619047 0.9814814814814815 0.6666666666666667 0.8323830756993447
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 41 1 0.5961662569198009 0.5638297872340425 0.9814814814814815 0.7162162162162162 0.8323830756993447
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 36 1 0.6170112309379757 0.5955056179775281 0.9814814814814815 0.7412587412587414 0.8323830756993447
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 25 2 0.6608268725942352 0.6753246753246753 0.9629629629629629 0.7938931297709924 0.8323876952869694
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 19 2 0.6925465624787586 0.7323943661971831 0.9629629629629629 0.832 0.8323876952869694
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 13 2 0.7274648765533178 0.8 0.9629629629629629 0.8739495798319328 0.8323876952869694
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 51 4 3 0.7797770575668476 0.9272727272727272 0.9444444444444444 0.9357798165137615 0.8332911693606508
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 68 3 0.30184866483914596 0.25274725274725274 0.8846153846153846 0.39316239316239315 0.7677455170908712
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 53 3 0.3462381743743145 0.3026315789473684 0.8846153846153846 0.45098039215686275 0.7677455170908712
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 43 3 0.3838727585454356 0.3484848484848485 0.8846153846153846 0.5 0.7677455170908712
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 36 4 0.40668742632222576 0.3793103448275862 0.8461538461538461 0.5238095238095238 0.7764032684333401
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 31 4 0.4324271368489489 0.41509433962264153 0.8461538461538461 0.5569620253164558 0.7764032684333401
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 23 5 0.4612904089758796 0.4772727272727273 0.8076923076923077 0.6000000000000001 0.7688173482931326
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 15 6 0.501544578192486 0.5714285714285714 0.7692307692307693 0.6557377049180327 0.7648554817435411
438
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 20 0 0.5731665590343088 0.5238095238095238 1.0 0.6875000000000001 0.8336968131408128
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 13 1 0.6274894139828582 0.6176470588235294 0.9545454545454546 0.75 0.8366525519771442
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 11 1 0.6507297626488899 0.65625 0.9545454545454546 0.7777777777777778 0.8366525519771442
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 10 1 0.663007682698869 0.6774193548387096 0.9545454545454546 0.7924528301886793 0.8366525519771442
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 10 1 0.663007682698869 0.6774193548387096 0.9545454545454546 0.7924528301886793 0.8366525519771442
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 8 1 0.6890079839811776 0.7241379310344828 0.9545454545454546 0.823529411764706 0.8366525519771442
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 5 3 0.6917586131069555 0.7916666666666666 0.8636363636363636 0.8260869565217391 0.8373920053399988
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 41 1 0.44710161046040403 0.3880597014925373 0.9629629629629629 0.553191489361702 0.808222141986115
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 35 1 0.47758581117361343 0.4262295081967213 0.9629629629629629 0.5909090909090909 0.808222141986115
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 27 1 0.5205965533357929 0.49056603773584906 0.9629629629629629 0.65 0.8009177743627584
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 20 1 0.5705167707789511 0.5652173913043478 0.9629629629629629 0.7123287671232876 0.8009177743627584
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 17 3 0.5728935651202653 0.5853658536585366 0.8888888888888888 0.7058823529411764 0.8115992172537093
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 14 4 0.5813049324208015 0.6216216216216216 0.8518518518518519 0.7187499999999999 0.8087720798898108
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 6 0.6152196467652105 0.7777777777777778 0.7777777777777778 0.7777777777777778 0.7909966886981278
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 12 10 0.5697235213427492 0.6571428571428571 0.696969696969697 0.676470588235294 0.84219998807189
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 10 10 0.5869878704743475 0.696969696969697 0.696969696969697 0.696969696969697 0.84219998807189
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 7 12 0.594053957464425 0.75 0.6363636363636364 0.6885245901639345 0.8627926525078554
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 12 0.6039548567554988 0.7777777777777778 0.6363636363636364 0.7000000000000001 0.8627926525078554
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 4 12 0.6247808862987918 0.84 0.6363636363636364 0.7241379310344828 0.8627926525078554
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 4 13 0.6069781845896316 0.8333333333333334 0.6060606060606061 0.7017543859649124 0.864943913040225
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 2 15 0.5888948931389513 0.9 0.5454545454545454 0.679245283018868 0.8669841482323448
299
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 14 9 0.5551036051470244 0.6744186046511628 0.7631578947368421 0.7160493827160495 0.7752308968432582
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 11 9 0.5764537438065254 0.725 0.7631578947368421 0.7435897435897436 0.7752308968432582
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 7 9 0.6076134056339051 0.8055555555555556 0.7631578947368421 0.7837837837837838 0.7752308968432582
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 6 12 0.5835012734716382 0.8125 0.6842105263157895 0.742857142857143 0.7854824835195129
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 5 14 0.5684434639797412 0.8275862068965517 0.631578947368421 0.716417910447761 0.7934523351383888
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 3 14 0.5859340321021947 0.8888888888888888 0.631578947368421 0.7384615384615385 0.7934523351383888
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 1 19 0.5271950472390986 0.95 0.5 0.6551724137931034 0.8046661247333611
613
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 47 60 4 0.48535025865836007 0.4392523364485981 0.9215686274509803 0.5949367088607594 0.8158014985959668
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 47 52 4 0.5112356057868059 0.47474747474747475 0.9215686274509803 0.6266666666666666 0.8158014985959668
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 46 44 5 0.5294134542310958 0.5111111111111111 0.9019607843137255 0.652482269503546 0.8113836635498315
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 44 28 7 0.5812565791658437 0.6111111111111112 0.8627450980392157 0.7154471544715448 0.8124381731522589
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 43 28 8 0.574963941836602 0.6056338028169014 0.8431372549019608 0.7049180327868853 0.8156465221402959
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 39 16 12 0.5953074972408575 0.7090909090909091 0.7647058823529411 0.7358490566037736 0.8090076244555243
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 34 7 17 0.6006003304950215 0.8292682926829268 0.6666666666666666 0.7391304347826086 0.8125769177285586
1195
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 89 64 24 0.5484881967555755 0.5816993464052288 0.7876106194690266 0.6691729323308271 0.8196509007695679
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 88 54 25 0.5674150244395908 0.6197183098591549 0.7787610619469026 0.6901960784313725 0.8221069956369071
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 87 42 26 0.5904155415931948 0.6744186046511628 0.7699115044247787 0.71900826446281 0.8211526498020295
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 80 33 33 0.5910453025983493 0.7079646017699115 0.7079646017699115 0.7079646017699115 0.8348514899201683
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 75 25 38 0.5909939687752785 0.75 0.6637168141592921 0.7042253521126761 0.8392114356608956
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 71 16 42 0.5988852665747906 0.8160919540229885 0.6283185840707964 0.71 0.8435003754574516
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 62 7 51 0.5770305717405755 0.8985507246376812 0.5486725663716814 0.6813186813186812 0.8469319681998769

             pq  f1_score  precision    recall       iou
thres
0.50   0.487192  0.597299   0.491087  0.824000  0.811195
0.60   0.515346  0.631170   0.538544  0.815637  0.812273
0.70   0.539043  0.659505   0.588395  0.803088  0.813628
0.80   0.558661  0.679730   0.636142  0.775891  0.818681
0.85   0.566661  0.686497   0.666754  0.754057  0.821975
0.90   0.580986  0.704416   0.720046  0.728205  0.821712
0.95   0.582469  0.704343   0.825306  0.651209  0.825612

## Tellu

In [ ]:
ds = dl.Tellu(split='test')
pq_data = []
for idx in range(len(ds)):
    im, gt_mask, gt_boxes, im_path, im_ID = ds[idx]
    im, flatfield = dl.normalize(im)

    H, W = im.shape[:2]
    # patch_size = int(np.ceil(max(H, W) * 7 / 12))
    patch_size = 512
    print(patch_size)

    contours, boxes, scores = samos.forward(im, patch_size=patch_size, predict_masks=True)
    for thres in [0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.95]:
        contours, boxes, scores = samos.set_threshold(conf_thres=thres, predict_masks=True)
        if contours is not None:
            iou_matrix = pp.compute_iou_matrix_segmentation_contours(contours, pp.convert_mask_to_binary(gt_mask).astype(np.uint8))
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_segmentation_from_iou_matrix(iou_matrix=iou_matrix)
        else:
            iou_matrix = pp.compute_iou_matrix_detection(boxes, gt_boxes)
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_detection_from_iou_matrix(iou_matrix=iou_matrix)

        print("Threshold", thres)
        print("tp, fp, fn, pq, precision, recall, f1_score, mean_iou:", tp, fp, fn, pq, precision, recall, f1_score, mean_iou)
        pq_data.append((f'{thres:4.2f}', pq, f1_score, precision, recall, mean_iou))


        fig, ax = plt.subplots(1, 1, figsize=(12*4, 12*4), dpi=200)
        plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
        plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
        plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
        plot_dir.mkdir(exist_ok=True)
        plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_{int(thres*100)}.png', dpi=200)
        plt.close('all')

    # fig, ax = plt.subplots(1, 1, figsize=(10, 10), dpi=80)
    # plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    # plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')

pq_data = pd.DataFrame(data=pq_data, columns=["thres", "pq", "f1_score", "precision", "recall", "iou"])
pq_data.to_csv(results_dir / f'test_metrics_added_eval_{str(ds)}_{ds.split}.csv', index=False)

pq_data.groupby('thres').mean()
# plot_boxes(im, boxes, format='yxyx_px')

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

976
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 64 107 116 0.2758711760212687 0.3742690058479532 0.35555555555555557 0.36467236467236464 0.7564904904958228
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 61 89 119 0.2815202601479259 0.4066666666666667 0.3388888888888889 0.36969696969696975 0.76148922826898
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 59 71 121 0.2911250693925507 0.45384615384615384 0.3277777777777778 0.3806451612903226 0.7648200975567009
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 52 125 0.2994225568747437 0.514018691588785 0.3055555555555556 0.3832752613240418 0.7812206711186493
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 50 44 130 0.2875695909761604 0.5319148936170213 0.2777777777777778 0.36496350364963503 0.7879406792746795
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 43 36 137 0.26428264165667786 0.5443037974683544 0.2388888888888889 0.33204633204633205 0.7959209789427857
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 36 14 144 0.2562414522999078 0.72 0.2 0.3130434782608696 0.8185490837358166
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 70 66 9 0.5603459999469422 0.5147058823529411 0.8860759493670886 0.6511627906976745 0.8605313570613755
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 69 56 10 0.5823724411939895 0.552 0.8734177215189873 0.6764705882352942 0.8608983913302453
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 67 45 12 0.6055967370489593 0.5982142857142857 0.8481012658227848 0.7015706806282722 0.8632013192265017
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 37 13 0.626391605762669 0.6407766990291263 0.8354430379746836 0.7252747252747253 0.8636611534000435
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 28 13 0.6589784523052356 0.7021276595744681 0.8354430379746836 0.7630057803468209 0.8636611534000435
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 18 13 0.6994065782135321 0.7857142857142857 0.8354430379746836 0.8098159509202455 0.8636611534000435
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 7 24 0.6864309603135166 0.8870967741935484 0.6962025316455697 0.7801418439716311 0.8798796854927804
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 52 1 0.5549220504662298 0.5047619047619047 0.9814814814814815 0.6666666666666667 0.8323830756993447
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 41 1 0.5961662569198009 0.5638297872340425 0.9814814814814815 0.7162162162162162 0.8323830756993447
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 36 1 0.6170112309379757 0.5955056179775281 0.9814814814814815 0.7412587412587414 0.8323830756993447
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 25 2 0.6608268725942352 0.6753246753246753 0.9629629629629629 0.7938931297709924 0.8323876952869694
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 19 2 0.6925465624787586 0.7323943661971831 0.9629629629629629 0.832 0.8323876952869694
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 13 2 0.7274648765533178 0.8 0.9629629629629629 0.8739495798319328 0.8323876952869694
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 51 4 3 0.7797770575668476 0.9272727272727272 0.9444444444444444 0.9357798165137615 0.8332911693606508
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 68 3 0.30184866483914596 0.25274725274725274 0.8846153846153846 0.39316239316239315 0.7677455170908712
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 53 3 0.3462381743743145 0.3026315789473684 0.8846153846153846 0.45098039215686275 0.7677455170908712
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 43 3 0.3838727585454356 0.3484848484848485 0.8846153846153846 0.5 0.7677455170908712
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 36 4 0.40668742632222576 0.3793103448275862 0.8461538461538461 0.5238095238095238 0.7764032684333401
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 31 4 0.4324271368489489 0.41509433962264153 0.8461538461538461 0.5569620253164558 0.7764032684333401
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 23 5 0.4612904089758796 0.4772727272727273 0.8076923076923077 0.6000000000000001 0.7688173482931326
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 15 6 0.501544578192486 0.5714285714285714 0.7692307692307693 0.6557377049180327 0.7648554817435411
438
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 20 0 0.5731665590343088 0.5238095238095238 1.0 0.6875000000000001 0.8336968131408128
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 13 1 0.6274894139828582 0.6176470588235294 0.9545454545454546 0.75 0.8366525519771442
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 11 1 0.6507297626488899 0.65625 0.9545454545454546 0.7777777777777778 0.8366525519771442
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 10 1 0.663007682698869 0.6774193548387096 0.9545454545454546 0.7924528301886793 0.8366525519771442
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 10 1 0.663007682698869 0.6774193548387096 0.9545454545454546 0.7924528301886793 0.8366525519771442
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 8 1 0.6890079839811776 0.7241379310344828 0.9545454545454546 0.823529411764706 0.8366525519771442
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 5 3 0.6917586131069555 0.7916666666666666 0.8636363636363636 0.8260869565217391 0.8373920053399988
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 41 1 0.44710161046040403 0.3880597014925373 0.9629629629629629 0.553191489361702 0.808222141986115
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 35 1 0.47758581117361343 0.4262295081967213 0.9629629629629629 0.5909090909090909 0.808222141986115
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 27 1 0.5205965533357929 0.49056603773584906 0.9629629629629629 0.65 0.8009177743627584
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 20 1 0.5705167707789511 0.5652173913043478 0.9629629629629629 0.7123287671232876 0.8009177743627584
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 17 3 0.5728935651202653 0.5853658536585366 0.8888888888888888 0.7058823529411764 0.8115992172537093
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 14 4 0.5813049324208015 0.6216216216216216 0.8518518518518519 0.7187499999999999 0.8087720798898108
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 6 0.6152196467652105 0.7777777777777778 0.7777777777777778 0.7777777777777778 0.7909966886981278
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 12 10 0.5697235213427492 0.6571428571428571 0.696969696969697 0.676470588235294 0.84219998807189
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 10 10 0.5869878704743475 0.696969696969697 0.696969696969697 0.696969696969697 0.84219998807189
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 7 12 0.594053957464425 0.75 0.6363636363636364 0.6885245901639345 0.8627926525078554
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 12 0.6039548567554988 0.7777777777777778 0.6363636363636364 0.7000000000000001 0.8627926525078554
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 4 12 0.6247808862987918 0.84 0.6363636363636364 0.7241379310344828 0.8627926525078554
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 4 13 0.6069781845896316 0.8333333333333334 0.6060606060606061 0.7017543859649124 0.864943913040225
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 2 15 0.5888948931389513 0.9 0.5454545454545454 0.679245283018868 0.8669841482323448
299
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 14 9 0.5551036051470244 0.6744186046511628 0.7631578947368421 0.7160493827160495 0.7752308968432582
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 11 9 0.5764537438065254 0.725 0.7631578947368421 0.7435897435897436 0.7752308968432582
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 7 9 0.6076134056339051 0.8055555555555556 0.7631578947368421 0.7837837837837838 0.7752308968432582
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 6 12 0.5835012734716382 0.8125 0.6842105263157895 0.742857142857143 0.7854824835195129
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 5 14 0.5684434639797412 0.8275862068965517 0.631578947368421 0.716417910447761 0.7934523351383888
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 3 14 0.5859340321021947 0.8888888888888888 0.631578947368421 0.7384615384615385 0.7934523351383888
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 1 19 0.5271950472390986 0.95 0.5 0.6551724137931034 0.8046661247333611
613
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 47 60 4 0.48535025865836007 0.4392523364485981 0.9215686274509803 0.5949367088607594 0.8158014985959668
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 47 52 4 0.5112356057868059 0.47474747474747475 0.9215686274509803 0.6266666666666666 0.8158014985959668
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 46 44 5 0.5294134542310958 0.5111111111111111 0.9019607843137255 0.652482269503546 0.8113836635498315
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 44 28 7 0.5812565791658437 0.6111111111111112 0.8627450980392157 0.7154471544715448 0.8124381731522589
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 43 28 8 0.574963941836602 0.6056338028169014 0.8431372549019608 0.7049180327868853 0.8156465221402959
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 39 16 12 0.5953074972408575 0.7090909090909091 0.7647058823529411 0.7358490566037736 0.8090076244555243
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 34 7 17 0.6006003304950215 0.8292682926829268 0.6666666666666666 0.7391304347826086 0.8125769177285586
1195
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 89 64 24 0.5484881967555755 0.5816993464052288 0.7876106194690266 0.6691729323308271 0.8196509007695679
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 88 54 25 0.5674150244395908 0.6197183098591549 0.7787610619469026 0.6901960784313725 0.8221069956369071
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 87 42 26 0.5904155415931948 0.6744186046511628 0.7699115044247787 0.71900826446281 0.8211526498020295
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 80 33 33 0.5910453025983493 0.7079646017699115 0.7079646017699115 0.7079646017699115 0.8348514899201683
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 75 25 38 0.5909939687752785 0.75 0.6637168141592921 0.7042253521126761 0.8392114356608956
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 71 16 42 0.5988852665747906 0.8160919540229885 0.6283185840707964 0.71 0.8435003754574516
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 62 7 51 0.5770305717405755 0.8985507246376812 0.5486725663716814 0.6813186813186812 0.8469319681998769

             pq  f1_score  precision    recall       iou
thres
0.50   0.487192  0.597299   0.491087  0.824000  0.811195
0.60   0.515346  0.631170   0.538544  0.815637  0.812273
0.70   0.539043  0.659505   0.588395  0.803088  0.813628
0.80   0.558661  0.679730   0.636142  0.775891  0.818681
0.85   0.566661  0.686497   0.666754  0.754057  0.821975
0.90   0.580986  0.704416   0.720046  0.728205  0.821712
0.95   0.582469  0.704343   0.825306  0.651209  0.825612

## MultiOrg

In [ ]:
ds = dl.MultiOrg(split='test_normal')
pq_data = []
for idx in range(len(ds)):
    im, gt_mask, gt_boxes, im_path, im_ID = ds[idx]
    # im, flatfield = dl.normalize(im)
    im = (im / im.max() * 255).astype(np.uint8)
    im = np.stack((im, im, im), axis=2)

    H, W = im.shape[:2]
    patch_size = 512
    print(patch_size)

    contours, boxes, scores = samos.forward(im, patch_size=patch_size, predict_masks=True)
    for thres in [0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.95]:
        contours, boxes, scores = samos.set_threshold(conf_thres=thres, predict_masks=True)
        if contours is not None:
            iou_matrix = pp.compute_iou_matrix_segmentation_contours(contours, pp.convert_mask_to_binary(gt_mask).astype(np.uint8))
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_segmentation_from_iou_matrix(iou_matrix=iou_matrix)
        else:
            iou_matrix = pp.compute_iou_matrix_detection(boxes, gt_boxes)
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_detection_from_iou_matrix(iou_matrix=iou_matrix)

        print("Threshold", thres)
        print("tp, fp, fn, pq, precision, recall, f1_score, mean_iou:", tp, fp, fn, pq, precision, recall, f1_score, mean_iou)
        pq_data.append((f'{thres:4.2f}', pq, f1_score, precision, recall, mean_iou))


        fig, ax = plt.subplots(1, 1, figsize=(12*4, 12*4), dpi=200)
        plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
        plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
        plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
        plot_dir.mkdir(exist_ok=True)
        plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_{int(thres*100)}.png', dpi=200)
        plt.close('all')

    # fig, ax = plt.subplots(1, 1, figsize=(10, 10), dpi=80)
    # plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    # plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')

pq_data = pd.DataFrame(data=pq_data, columns=["thres", "pq", "f1_score", "precision", "recall", "iou"])
pq_data.to_csv(results_dir / f'test_metrics_added_eval_{str(ds)}_{ds.split}.csv', index=False)

pq_data.groupby('thres').mean()
# plot_boxes(im, boxes, format='yxyx_px')

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

976
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 64 107 116 0.2758711760212687 0.3742690058479532 0.35555555555555557 0.36467236467236464 0.7564904904958228
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 61 89 119 0.2815202601479259 0.4066666666666667 0.3388888888888889 0.36969696969696975 0.76148922826898
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 59 71 121 0.2911250693925507 0.45384615384615384 0.3277777777777778 0.3806451612903226 0.7648200975567009
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 52 125 0.2994225568747437 0.514018691588785 0.3055555555555556 0.3832752613240418 0.7812206711186493
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 50 44 130 0.2875695909761604 0.5319148936170213 0.2777777777777778 0.36496350364963503 0.7879406792746795
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 43 36 137 0.26428264165667786 0.5443037974683544 0.2388888888888889 0.33204633204633205 0.7959209789427857
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 36 14 144 0.2562414522999078 0.72 0.2 0.3130434782608696 0.8185490837358166
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 70 66 9 0.5603459999469422 0.5147058823529411 0.8860759493670886 0.6511627906976745 0.8605313570613755
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 69 56 10 0.5823724411939895 0.552 0.8734177215189873 0.6764705882352942 0.8608983913302453
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 67 45 12 0.6055967370489593 0.5982142857142857 0.8481012658227848 0.7015706806282722 0.8632013192265017
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 37 13 0.626391605762669 0.6407766990291263 0.8354430379746836 0.7252747252747253 0.8636611534000435
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 28 13 0.6589784523052356 0.7021276595744681 0.8354430379746836 0.7630057803468209 0.8636611534000435
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 18 13 0.6994065782135321 0.7857142857142857 0.8354430379746836 0.8098159509202455 0.8636611534000435
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 7 24 0.6864309603135166 0.8870967741935484 0.6962025316455697 0.7801418439716311 0.8798796854927804
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 52 1 0.5549220504662298 0.5047619047619047 0.9814814814814815 0.6666666666666667 0.8323830756993447
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 41 1 0.5961662569198009 0.5638297872340425 0.9814814814814815 0.7162162162162162 0.8323830756993447
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 36 1 0.6170112309379757 0.5955056179775281 0.9814814814814815 0.7412587412587414 0.8323830756993447
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 25 2 0.6608268725942352 0.6753246753246753 0.9629629629629629 0.7938931297709924 0.8323876952869694
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 19 2 0.6925465624787586 0.7323943661971831 0.9629629629629629 0.832 0.8323876952869694
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 13 2 0.7274648765533178 0.8 0.9629629629629629 0.8739495798319328 0.8323876952869694
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 51 4 3 0.7797770575668476 0.9272727272727272 0.9444444444444444 0.9357798165137615 0.8332911693606508
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 68 3 0.30184866483914596 0.25274725274725274 0.8846153846153846 0.39316239316239315 0.7677455170908712
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 53 3 0.3462381743743145 0.3026315789473684 0.8846153846153846 0.45098039215686275 0.7677455170908712
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 43 3 0.3838727585454356 0.3484848484848485 0.8846153846153846 0.5 0.7677455170908712
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 36 4 0.40668742632222576 0.3793103448275862 0.8461538461538461 0.5238095238095238 0.7764032684333401
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 31 4 0.4324271368489489 0.41509433962264153 0.8461538461538461 0.5569620253164558 0.7764032684333401
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 23 5 0.4612904089758796 0.4772727272727273 0.8076923076923077 0.6000000000000001 0.7688173482931326
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 15 6 0.501544578192486 0.5714285714285714 0.7692307692307693 0.6557377049180327 0.7648554817435411
438
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 20 0 0.5731665590343088 0.5238095238095238 1.0 0.6875000000000001 0.8336968131408128
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 13 1 0.6274894139828582 0.6176470588235294 0.9545454545454546 0.75 0.8366525519771442
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 11 1 0.6507297626488899 0.65625 0.9545454545454546 0.7777777777777778 0.8366525519771442
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 10 1 0.663007682698869 0.6774193548387096 0.9545454545454546 0.7924528301886793 0.8366525519771442
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 10 1 0.663007682698869 0.6774193548387096 0.9545454545454546 0.7924528301886793 0.8366525519771442
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 8 1 0.6890079839811776 0.7241379310344828 0.9545454545454546 0.823529411764706 0.8366525519771442
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 5 3 0.6917586131069555 0.7916666666666666 0.8636363636363636 0.8260869565217391 0.8373920053399988
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 41 1 0.44710161046040403 0.3880597014925373 0.9629629629629629 0.553191489361702 0.808222141986115
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 35 1 0.47758581117361343 0.4262295081967213 0.9629629629629629 0.5909090909090909 0.808222141986115
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 27 1 0.5205965533357929 0.49056603773584906 0.9629629629629629 0.65 0.8009177743627584
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 20 1 0.5705167707789511 0.5652173913043478 0.9629629629629629 0.7123287671232876 0.8009177743627584
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 17 3 0.5728935651202653 0.5853658536585366 0.8888888888888888 0.7058823529411764 0.8115992172537093
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 14 4 0.5813049324208015 0.6216216216216216 0.8518518518518519 0.7187499999999999 0.8087720798898108
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 6 0.6152196467652105 0.7777777777777778 0.7777777777777778 0.7777777777777778 0.7909966886981278
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 12 10 0.5697235213427492 0.6571428571428571 0.696969696969697 0.676470588235294 0.84219998807189
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 10 10 0.5869878704743475 0.696969696969697 0.696969696969697 0.696969696969697 0.84219998807189
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 7 12 0.594053957464425 0.75 0.6363636363636364 0.6885245901639345 0.8627926525078554
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 12 0.6039548567554988 0.7777777777777778 0.6363636363636364 0.7000000000000001 0.8627926525078554
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 4 12 0.6247808862987918 0.84 0.6363636363636364 0.7241379310344828 0.8627926525078554
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 4 13 0.6069781845896316 0.8333333333333334 0.6060606060606061 0.7017543859649124 0.864943913040225
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 2 15 0.5888948931389513 0.9 0.5454545454545454 0.679245283018868 0.8669841482323448
299
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 14 9 0.5551036051470244 0.6744186046511628 0.7631578947368421 0.7160493827160495 0.7752308968432582
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 11 9 0.5764537438065254 0.725 0.7631578947368421 0.7435897435897436 0.7752308968432582
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 7 9 0.6076134056339051 0.8055555555555556 0.7631578947368421 0.7837837837837838 0.7752308968432582
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 6 12 0.5835012734716382 0.8125 0.6842105263157895 0.742857142857143 0.7854824835195129
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 5 14 0.5684434639797412 0.8275862068965517 0.631578947368421 0.716417910447761 0.7934523351383888
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 3 14 0.5859340321021947 0.8888888888888888 0.631578947368421 0.7384615384615385 0.7934523351383888
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 1 19 0.5271950472390986 0.95 0.5 0.6551724137931034 0.8046661247333611
613
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 47 60 4 0.48535025865836007 0.4392523364485981 0.9215686274509803 0.5949367088607594 0.8158014985959668
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 47 52 4 0.5112356057868059 0.47474747474747475 0.9215686274509803 0.6266666666666666 0.8158014985959668
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 46 44 5 0.5294134542310958 0.5111111111111111 0.9019607843137255 0.652482269503546 0.8113836635498315
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 44 28 7 0.5812565791658437 0.6111111111111112 0.8627450980392157 0.7154471544715448 0.8124381731522589
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 43 28 8 0.574963941836602 0.6056338028169014 0.8431372549019608 0.7049180327868853 0.8156465221402959
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 39 16 12 0.5953074972408575 0.7090909090909091 0.7647058823529411 0.7358490566037736 0.8090076244555243
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 34 7 17 0.6006003304950215 0.8292682926829268 0.6666666666666666 0.7391304347826086 0.8125769177285586
1195
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 89 64 24 0.5484881967555755 0.5816993464052288 0.7876106194690266 0.6691729323308271 0.8196509007695679
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 88 54 25 0.5674150244395908 0.6197183098591549 0.7787610619469026 0.6901960784313725 0.8221069956369071
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 87 42 26 0.5904155415931948 0.6744186046511628 0.7699115044247787 0.71900826446281 0.8211526498020295
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 80 33 33 0.5910453025983493 0.7079646017699115 0.7079646017699115 0.7079646017699115 0.8348514899201683
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 75 25 38 0.5909939687752785 0.75 0.6637168141592921 0.7042253521126761 0.8392114356608956
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 71 16 42 0.5988852665747906 0.8160919540229885 0.6283185840707964 0.71 0.8435003754574516
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 62 7 51 0.5770305717405755 0.8985507246376812 0.5486725663716814 0.6813186813186812 0.8469319681998769

             pq  f1_score  precision    recall       iou
thres
0.50   0.487192  0.597299   0.491087  0.824000  0.811195
0.60   0.515346  0.631170   0.538544  0.815637  0.812273
0.70   0.539043  0.659505   0.588395  0.803088  0.813628
0.80   0.558661  0.679730   0.636142  0.775891  0.818681
0.85   0.566661  0.686497   0.666754  0.754057  0.821975
0.90   0.580986  0.704416   0.720046  0.728205  0.821712
0.95   0.582469  0.704343   0.825306  0.651209  0.825612

In [ ]:
ds = dl.MultiOrg(split='test_macros')
pq_data = []
for idx in range(len(ds)):
    im, gt_mask, gt_boxes, im_path, im_ID = ds[idx]
    # im, flatfield = dl.normalize(im)
    im = (im / im.max() * 255).astype(np.uint8)
    im = np.stack((im, im, im), axis=2)

    H, W = im.shape[:2]
    patch_size = 512
    print(patch_size)

    contours, boxes, scores = samos.forward(im, patch_size=patch_size, predict_masks=True)
    for thres in [0.5, 0.6, 0.7, 0.8, 0.85, 0.9, 0.95]:
        contours, boxes, scores = samos.set_threshold(conf_thres=thres, predict_masks=True)
        if contours is not None:
            iou_matrix = pp.compute_iou_matrix_segmentation_contours(contours, pp.convert_mask_to_binary(gt_mask).astype(np.uint8))
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_segmentation_from_iou_matrix(iou_matrix=iou_matrix)
        else:
            iou_matrix = pp.compute_iou_matrix_detection(boxes, gt_boxes)
            tp, fp, fn, pq, precision, recall, f1_score, mean_iou, dice = \
                pp.compute_metrics_detection_from_iou_matrix(iou_matrix=iou_matrix)

        print("Threshold", thres)
        print("tp, fp, fn, pq, precision, recall, f1_score, mean_iou:", tp, fp, fn, pq, precision, recall, f1_score, mean_iou)
        pq_data.append((f'{thres:4.2f}', pq, f1_score, precision, recall, mean_iou))


        fig, ax = plt.subplots(1, 1, figsize=(12*4, 12*4), dpi=200)
        plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
        plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
        plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
        plot_dir.mkdir(exist_ok=True)
        plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_{int(thres*100)}.png', dpi=200)
        plt.close('all')

    # fig, ax = plt.subplots(1, 1, figsize=(10, 10), dpi=80)
    # plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    # plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')

pq_data = pd.DataFrame(data=pq_data, columns=["thres", "pq", "f1_score", "precision", "recall", "iou"])
pq_data.to_csv(results_dir / f'test_metrics_added_eval_{str(ds)}_{ds.split}.csv', index=False)

pq_data.groupby('thres').mean()
# plot_boxes(im, boxes, format='yxyx_px')

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

976
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 64 107 116 0.2758711760212687 0.3742690058479532 0.35555555555555557 0.36467236467236464 0.7564904904958228
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 61 89 119 0.2815202601479259 0.4066666666666667 0.3388888888888889 0.36969696969696975 0.76148922826898
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 59 71 121 0.2911250693925507 0.45384615384615384 0.3277777777777778 0.3806451612903226 0.7648200975567009
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 52 125 0.2994225568747437 0.514018691588785 0.3055555555555556 0.3832752613240418 0.7812206711186493
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 50 44 130 0.2875695909761604 0.5319148936170213 0.2777777777777778 0.36496350364963503 0.7879406792746795
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 43 36 137 0.26428264165667786 0.5443037974683544 0.2388888888888889 0.33204633204633205 0.7959209789427857
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 36 14 144 0.2562414522999078 0.72 0.2 0.3130434782608696 0.8185490837358166
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 70 66 9 0.5603459999469422 0.5147058823529411 0.8860759493670886 0.6511627906976745 0.8605313570613755
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 69 56 10 0.5823724411939895 0.552 0.8734177215189873 0.6764705882352942 0.8608983913302453
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 67 45 12 0.6055967370489593 0.5982142857142857 0.8481012658227848 0.7015706806282722 0.8632013192265017
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 37 13 0.626391605762669 0.6407766990291263 0.8354430379746836 0.7252747252747253 0.8636611534000435
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 28 13 0.6589784523052356 0.7021276595744681 0.8354430379746836 0.7630057803468209 0.8636611534000435
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 66 18 13 0.6994065782135321 0.7857142857142857 0.8354430379746836 0.8098159509202455 0.8636611534000435
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 55 7 24 0.6864309603135166 0.8870967741935484 0.6962025316455697 0.7801418439716311 0.8798796854927804
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 52 1 0.5549220504662298 0.5047619047619047 0.9814814814814815 0.6666666666666667 0.8323830756993447
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 41 1 0.5961662569198009 0.5638297872340425 0.9814814814814815 0.7162162162162162 0.8323830756993447
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 53 36 1 0.6170112309379757 0.5955056179775281 0.9814814814814815 0.7412587412587414 0.8323830756993447
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 25 2 0.6608268725942352 0.6753246753246753 0.9629629629629629 0.7938931297709924 0.8323876952869694
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 19 2 0.6925465624787586 0.7323943661971831 0.9629629629629629 0.832 0.8323876952869694
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 52 13 2 0.7274648765533178 0.8 0.9629629629629629 0.8739495798319328 0.8323876952869694
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 51 4 3 0.7797770575668476 0.9272727272727272 0.9444444444444444 0.9357798165137615 0.8332911693606508
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 68 3 0.30184866483914596 0.25274725274725274 0.8846153846153846 0.39316239316239315 0.7677455170908712
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 53 3 0.3462381743743145 0.3026315789473684 0.8846153846153846 0.45098039215686275 0.7677455170908712
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 43 3 0.3838727585454356 0.3484848484848485 0.8846153846153846 0.5 0.7677455170908712
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 36 4 0.40668742632222576 0.3793103448275862 0.8461538461538461 0.5238095238095238 0.7764032684333401
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 31 4 0.4324271368489489 0.41509433962264153 0.8461538461538461 0.5569620253164558 0.7764032684333401
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 23 5 0.4612904089758796 0.4772727272727273 0.8076923076923077 0.6000000000000001 0.7688173482931326
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 15 6 0.501544578192486 0.5714285714285714 0.7692307692307693 0.6557377049180327 0.7648554817435411
438
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 22 20 0 0.5731665590343088 0.5238095238095238 1.0 0.6875000000000001 0.8336968131408128
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 13 1 0.6274894139828582 0.6176470588235294 0.9545454545454546 0.75 0.8366525519771442
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 11 1 0.6507297626488899 0.65625 0.9545454545454546 0.7777777777777778 0.8366525519771442
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 10 1 0.663007682698869 0.6774193548387096 0.9545454545454546 0.7924528301886793 0.8366525519771442
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 10 1 0.663007682698869 0.6774193548387096 0.9545454545454546 0.7924528301886793 0.8366525519771442
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 8 1 0.6890079839811776 0.7241379310344828 0.9545454545454546 0.823529411764706 0.8366525519771442
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 5 3 0.6917586131069555 0.7916666666666666 0.8636363636363636 0.8260869565217391 0.8373920053399988
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 41 1 0.44710161046040403 0.3880597014925373 0.9629629629629629 0.553191489361702 0.808222141986115
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 35 1 0.47758581117361343 0.4262295081967213 0.9629629629629629 0.5909090909090909 0.808222141986115
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 27 1 0.5205965533357929 0.49056603773584906 0.9629629629629629 0.65 0.8009177743627584
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 20 1 0.5705167707789511 0.5652173913043478 0.9629629629629629 0.7123287671232876 0.8009177743627584
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 17 3 0.5728935651202653 0.5853658536585366 0.8888888888888888 0.7058823529411764 0.8115992172537093
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 14 4 0.5813049324208015 0.6216216216216216 0.8518518518518519 0.7187499999999999 0.8087720798898108
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 6 0.6152196467652105 0.7777777777777778 0.7777777777777778 0.7777777777777778 0.7909966886981278
598
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 12 10 0.5697235213427492 0.6571428571428571 0.696969696969697 0.676470588235294 0.84219998807189
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 23 10 10 0.5869878704743475 0.696969696969697 0.696969696969697 0.696969696969697 0.84219998807189
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 7 12 0.594053957464425 0.75 0.6363636363636364 0.6885245901639345 0.8627926525078554
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 6 12 0.6039548567554988 0.7777777777777778 0.6363636363636364 0.7000000000000001 0.8627926525078554
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 21 4 12 0.6247808862987918 0.84 0.6363636363636364 0.7241379310344828 0.8627926525078554
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 20 4 13 0.6069781845896316 0.8333333333333334 0.6060606060606061 0.7017543859649124 0.864943913040225
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 18 2 15 0.5888948931389513 0.9 0.5454545454545454 0.679245283018868 0.8669841482323448
299
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 14 9 0.5551036051470244 0.6744186046511628 0.7631578947368421 0.7160493827160495 0.7752308968432582
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 11 9 0.5764537438065254 0.725 0.7631578947368421 0.7435897435897436 0.7752308968432582
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 29 7 9 0.6076134056339051 0.8055555555555556 0.7631578947368421 0.7837837837837838 0.7752308968432582
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 26 6 12 0.5835012734716382 0.8125 0.6842105263157895 0.742857142857143 0.7854824835195129
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 5 14 0.5684434639797412 0.8275862068965517 0.631578947368421 0.716417910447761 0.7934523351383888
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 24 3 14 0.5859340321021947 0.8888888888888888 0.631578947368421 0.7384615384615385 0.7934523351383888
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 19 1 19 0.5271950472390986 0.95 0.5 0.6551724137931034 0.8046661247333611
613
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 47 60 4 0.48535025865836007 0.4392523364485981 0.9215686274509803 0.5949367088607594 0.8158014985959668
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 47 52 4 0.5112356057868059 0.47474747474747475 0.9215686274509803 0.6266666666666666 0.8158014985959668
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 46 44 5 0.5294134542310958 0.5111111111111111 0.9019607843137255 0.652482269503546 0.8113836635498315
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 44 28 7 0.5812565791658437 0.6111111111111112 0.8627450980392157 0.7154471544715448 0.8124381731522589
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 43 28 8 0.574963941836602 0.6056338028169014 0.8431372549019608 0.7049180327868853 0.8156465221402959
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 39 16 12 0.5953074972408575 0.7090909090909091 0.7647058823529411 0.7358490566037736 0.8090076244555243
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 34 7 17 0.6006003304950215 0.8292682926829268 0.6666666666666666 0.7391304347826086 0.8125769177285586
1195
Threshold 0.5
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 89 64 24 0.5484881967555755 0.5816993464052288 0.7876106194690266 0.6691729323308271 0.8196509007695679
Threshold 0.6
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 88 54 25 0.5674150244395908 0.6197183098591549 0.7787610619469026 0.6901960784313725 0.8221069956369071
Threshold 0.7
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 87 42 26 0.5904155415931948 0.6744186046511628 0.7699115044247787 0.71900826446281 0.8211526498020295
Threshold 0.8
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 80 33 33 0.5910453025983493 0.7079646017699115 0.7079646017699115 0.7079646017699115 0.8348514899201683
Threshold 0.85
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 75 25 38 0.5909939687752785 0.75 0.6637168141592921 0.7042253521126761 0.8392114356608956
Threshold 0.9
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 71 16 42 0.5988852665747906 0.8160919540229885 0.6283185840707964 0.71 0.8435003754574516
Threshold 0.95
tp, fp, fn, pq, precision, recall, f1_score, mean_iou: 62 7 51 0.5770305717405755 0.8985507246376812 0.5486725663716814 0.6813186813186812 0.8469319681998769

             pq  f1_score  precision    recall       iou
thres
0.50   0.487192  0.597299   0.491087  0.824000  0.811195
0.60   0.515346  0.631170   0.538544  0.815637  0.812273
0.70   0.539043  0.659505   0.588395  0.803088  0.813628
0.80   0.558661  0.679730   0.636142  0.775891  0.818681
0.85   0.566661  0.686497   0.666754  0.754057  0.821975
0.90   0.580986  0.704416   0.720046  0.728205  0.821712
0.95   0.582469  0.704343   0.825306  0.651209  0.825612

In [4]:
ds = dl.MultiOrg(split='test_normal')

for idx in range(len(ds)):
    if idx != 0:
        break

    im, gt_mask, gt_boxes, im_path, im_ID = ds[idx]
    im = (im / im.max() * 255).astype(np.uint8)
    im = np.stack((im, im, im), axis=2)

    
    masks, boxes, scores = samos.forward(im, patch_size=(300, 1024), predict_masks=True)
    masks, boxes, scores = samos.set_threshold(conf_thres=0.95, predict_masks=True)

    fig, ax = plt.subplots(1, 1, figsize=(12*2, 12*2), dpi=40)
    plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
    plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
    plot_dir.mkdir(exist_ok=True)
    plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_95.png', dpi=200)
    plt.close('all')
    
    masks, boxes, scores = samos.set_threshold(conf_thres=0.85, predict_masks=True)
    
    fig, ax = plt.subplots(1, 1, figsize=(12*2, 12*2), dpi=40)
    plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
    plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
    plot_dir.mkdir(exist_ok=True)
    plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_85.png', dpi=200)
    plt.close('all')
    
    masks, boxes, scores = samos.set_threshold(conf_thres=0.75, predict_masks=True)
    
    fig, ax = plt.subplots(1, 1, figsize=(12*2, 12*2), dpi=40)
    plot_boxes(im, gt_boxes, format='yxyx_px', ax=ax, color='blue')
    plot_boxes(im, boxes, format='yxyx_px', ax=ax, show_image=False, color='red')
    plot_dir = results_dir / 'plots' / 'MultiOrg_test_added_eval'
    plot_dir.mkdir(exist_ok=True)
    plt.savefig(plot_dir / f'{str(ds)}_{ds.split}_{idx}_thres_75.png', dpi=200)
    plt.close('all')